// GLFW-compatible API for Android -- GENERATED FILE, do not edit.
//
// Generated by tools/android/gen-glfw-shim-header.py from the vendored GLFW
// 3.5.1 header (modules/v4d/third/glfw/include/GLFW/glfw3.h). Every constant,
// typedef and structure below is copied from it verbatim, so key / button /
// gamepad tokens carry the same values on Android as on the desktop and code
// that branches on GLFW_VERSION_* (framebuffercontext.cpp does) behaves
// identically. The function declarations are the subset that
// modules/v4d/third/glfw-android implements on top of EGL, ANativeWindow and
// AInputQueue.
//
// GLFW itself has no Android backend, so this is what `#include <GLFW/glfw3.h>`
// resolves to when ANDROID is defined. That keeps FrameBufferContext,
// v4d/events.hpp, imguicontext.cpp and the samples free of platform #ifdefs.
//
// Implementation: modules/v4d/third/glfw-android/glfw_android.cpp
// Activity entry point: modules/v4d/third/glfw-android/android_main.cpp

#ifndef GLFW_GLFW3_H_
#define GLFW_GLFW3_H_

#if defined(GLFW_INCLUDE_NONE)
#undef GLFW_INCLUDE_NONE
#endif

#ifdef __cplusplus
extern "C" {
#endif

// ---- version and boolean tokens (verbatim) ----
#define GLFW_VERSION_MAJOR                       3
#define GLFW_VERSION_MINOR                       5
#define GLFW_VERSION_REVISION                    1
#define GLFW_TRUE                                1
#define GLFW_FALSE                               0

// ---- window hints and attributes ----
#define GLFW_ALPHA_BITS                          0x00021004
#define GLFW_AUTO_ICONIFY                        0x00020006
#define GLFW_AUX_BUFFERS                         0x0002100B
#define GLFW_BLUE_BITS                           0x00021003
#define GLFW_CENTER_CURSOR                       0x00020009
#define GLFW_CLIENT_API                          0x00022001
#define GLFW_CONTEXT_CREATION_API                0x0002200B
#define GLFW_CONTEXT_DEBUG                       0x00022007
#define GLFW_CONTEXT_NO_ERROR                    0x0002200A
#define GLFW_CONTEXT_RELEASE_BEHAVIOR            0x00022009
#define GLFW_CONTEXT_REVISION                    0x00022004
#define GLFW_CONTEXT_ROBUSTNESS                  0x00022005
#define GLFW_CONTEXT_VERSION_MAJOR               0x00022002
#define GLFW_CONTEXT_VERSION_MINOR               0x00022003
#define GLFW_DECORATED                           0x00020005
#define GLFW_DEPTH_BITS                          0x00021005
#define GLFW_DOUBLEBUFFER                        0x00021010
#define GLFW_FOCUSED                             0x00020001
#define GLFW_FOCUS_ON_SHOW                       0x0002000C
#define GLFW_GREEN_BITS                          0x00021002
#define GLFW_MAXIMIZED                           0x00020008
#define GLFW_OPENGL_ANY_PROFILE                  0
#define GLFW_OPENGL_API                          0x00030001
#define GLFW_OPENGL_COMPAT_PROFILE               0x00032002
#define GLFW_OPENGL_CORE_PROFILE                 0x00032001
#define GLFW_OPENGL_DEBUG_CONTEXT                GLFW_CONTEXT_DEBUG
#define GLFW_OPENGL_ES_API                       0x00030002
#define GLFW_OPENGL_FORWARD_COMPAT               0x00022006
#define GLFW_OPENGL_PROFILE                      0x00022008
#define GLFW_PLATFORM                            0x00050003
#define GLFW_PLATFORM_ANDROID                    0x00060006
#define GLFW_PLATFORM_COCOA                      0x00060002
#define GLFW_PLATFORM_ERROR                      0x00010008
#define GLFW_PLATFORM_NULL                       0x00060005
#define GLFW_PLATFORM_UNAVAILABLE                0x0001000E
#define GLFW_PLATFORM_WAYLAND                    0x00060003
#define GLFW_PLATFORM_WIN32                      0x00060001
#define GLFW_PLATFORM_X11                        0x00060004
#define GLFW_RED_BITS                            0x00021001
#define GLFW_RESIZABLE                           0x00020003
#define GLFW_SAMPLES                             0x0002100D
#define GLFW_SCALE_FRAMEBUFFER                   0x0002200D
#define GLFW_SCALE_TO_MONITOR                    0x0002200C
#define GLFW_STENCIL_BITS                        0x00021006
#define GLFW_TRANSPARENT_FRAMEBUFFER             0x0002000A
#define GLFW_VISIBLE                             0x00020004

// ---- input mode and modifier tokens ----
#define GLFW_CURSOR                              0x00033001
#define GLFW_CURSOR_CAPTURED                     0x00034004
#define GLFW_CURSOR_DISABLED                     0x00034003
#define GLFW_CURSOR_HIDDEN                       0x00034002
#define GLFW_CURSOR_NORMAL                       0x00034001
#define GLFW_CURSOR_UNAVAILABLE                  0x0001000B
#define GLFW_LOCK_KEY_MODS                       0x00033004
#define GLFW_MOD_ALT                             0x0004
#define GLFW_MOD_CAPS_LOCK                       0x0010
#define GLFW_MOD_CONTROL                         0x0002
#define GLFW_MOD_NUM_LOCK                        0x0020
#define GLFW_MOD_SHIFT                           0x0001
#define GLFW_MOD_SUPER                           0x0008
#define GLFW_RAW_MOUSE_MOTION                    0x00033005
#define GLFW_STICKY_KEYS                         0x00033002
#define GLFW_STICKY_MOUSE_BUTTONS                0x00033003

// ---- action tokens ----
#define GLFW_PRESS                               1
#define GLFW_RELEASE                             0
#define GLFW_REPEAT                              2

// ---- key tokens (verbatim, identical on every platform) ----
#define GLFW_KEY_0                               48
#define GLFW_KEY_1                               49
#define GLFW_KEY_2                               50
#define GLFW_KEY_3                               51
#define GLFW_KEY_4                               52
#define GLFW_KEY_5                               53
#define GLFW_KEY_6                               54
#define GLFW_KEY_7                               55
#define GLFW_KEY_8                               56
#define GLFW_KEY_9                               57
#define GLFW_KEY_A                               65
#define GLFW_KEY_APOSTROPHE                      39  /* ' */
#define GLFW_KEY_B                               66
#define GLFW_KEY_BACKSLASH                       92  /* \ */
#define GLFW_KEY_BACKSPACE                       259
#define GLFW_KEY_C                               67
#define GLFW_KEY_CAPS_LOCK                       280
#define GLFW_KEY_COMMA                           44  /* , */
#define GLFW_KEY_D                               68
#define GLFW_KEY_DELETE                          261
#define GLFW_KEY_DOWN                            264
#define GLFW_KEY_E                               69
#define GLFW_KEY_END                             269
#define GLFW_KEY_ENTER                           257
#define GLFW_KEY_EQUAL                           61  /* = */
#define GLFW_KEY_ESCAPE                          256
#define GLFW_KEY_F                               70
#define GLFW_KEY_F1                              290
#define GLFW_KEY_F10                             299
#define GLFW_KEY_F11                             300
#define GLFW_KEY_F12                             301
#define GLFW_KEY_F13                             302
#define GLFW_KEY_F14                             303
#define GLFW_KEY_F15                             304
#define GLFW_KEY_F16                             305
#define GLFW_KEY_F17                             306
#define GLFW_KEY_F18                             307
#define GLFW_KEY_F19                             308
#define GLFW_KEY_F2                              291
#define GLFW_KEY_F20                             309
#define GLFW_KEY_F21                             310
#define GLFW_KEY_F22                             311
#define GLFW_KEY_F23                             312
#define GLFW_KEY_F24                             313
#define GLFW_KEY_F25                             314
#define GLFW_KEY_F3                              292
#define GLFW_KEY_F4                              293
#define GLFW_KEY_F5                              294
#define GLFW_KEY_F6                              295
#define GLFW_KEY_F7                              296
#define GLFW_KEY_F8                              297
#define GLFW_KEY_F9                              298
#define GLFW_KEY_G                               71
#define GLFW_KEY_GRAVE_ACCENT                    96  /* ` */
#define GLFW_KEY_H                               72
#define GLFW_KEY_HOME                            268
#define GLFW_KEY_I                               73
#define GLFW_KEY_INSERT                          260
#define GLFW_KEY_J                               74
#define GLFW_KEY_K                               75
#define GLFW_KEY_KP_0                            320
#define GLFW_KEY_KP_1                            321
#define GLFW_KEY_KP_2                            322
#define GLFW_KEY_KP_3                            323
#define GLFW_KEY_KP_4                            324
#define GLFW_KEY_KP_5                            325
#define GLFW_KEY_KP_6                            326
#define GLFW_KEY_KP_7                            327
#define GLFW_KEY_KP_8                            328
#define GLFW_KEY_KP_9                            329
#define GLFW_KEY_KP_ADD                          334
#define GLFW_KEY_KP_DECIMAL                      330
#define GLFW_KEY_KP_DIVIDE                       331
#define GLFW_KEY_KP_ENTER                        335
#define GLFW_KEY_KP_EQUAL                        336
#define GLFW_KEY_KP_MULTIPLY                     332
#define GLFW_KEY_KP_SUBTRACT                     333
#define GLFW_KEY_L                               76
#define GLFW_KEY_LAST                            GLFW_KEY_MENU
#define GLFW_KEY_LEFT                            263
#define GLFW_KEY_LEFT_ALT                        342
#define GLFW_KEY_LEFT_BRACKET                    91  /* [ */
#define GLFW_KEY_LEFT_CONTROL                    341
#define GLFW_KEY_LEFT_SHIFT                      340
#define GLFW_KEY_LEFT_SUPER                      343
#define GLFW_KEY_M                               77
#define GLFW_KEY_MENU                            348
#define GLFW_KEY_MINUS                           45  /* - */
#define GLFW_KEY_N                               78
#define GLFW_KEY_NUM_LOCK                        282
#define GLFW_KEY_O                               79
#define GLFW_KEY_P                               80
#define GLFW_KEY_PAGE_DOWN                       267
#define GLFW_KEY_PAGE_UP                         266
#define GLFW_KEY_PAUSE                           284
#define GLFW_KEY_PERIOD                          46  /* . */
#define GLFW_KEY_PRINT_SCREEN                    283
#define GLFW_KEY_Q                               81
#define GLFW_KEY_R                               82
#define GLFW_KEY_RIGHT                           262
#define GLFW_KEY_RIGHT_ALT                       346
#define GLFW_KEY_RIGHT_BRACKET                   93  /* ] */
#define GLFW_KEY_RIGHT_CONTROL                   345
#define GLFW_KEY_RIGHT_SHIFT                     344
#define GLFW_KEY_RIGHT_SUPER                     347
#define GLFW_KEY_S                               83
#define GLFW_KEY_SCROLL_LOCK                     281
#define GLFW_KEY_SEMICOLON                       59  /* ; */
#define GLFW_KEY_SLASH                           47  /* / */
#define GLFW_KEY_SPACE                           32
#define GLFW_KEY_T                               84
#define GLFW_KEY_TAB                             258
#define GLFW_KEY_U                               85
#define GLFW_KEY_UNKNOWN                         -1
#define GLFW_KEY_UP                              265
#define GLFW_KEY_V                               86
#define GLFW_KEY_W                               87
#define GLFW_KEY_WORLD_1                         161 /* non-US #1 */
#define GLFW_KEY_WORLD_2                         162 /* non-US #2 */
#define GLFW_KEY_X                               88
#define GLFW_KEY_Y                               89
#define GLFW_KEY_Z                               90

// ---- mouse button tokens ----
#define GLFW_MOUSE_BUTTON_1                      0
#define GLFW_MOUSE_BUTTON_2                      1
#define GLFW_MOUSE_BUTTON_3                      2
#define GLFW_MOUSE_BUTTON_4                      3
#define GLFW_MOUSE_BUTTON_5                      4
#define GLFW_MOUSE_BUTTON_6                      5
#define GLFW_MOUSE_BUTTON_7                      6
#define GLFW_MOUSE_BUTTON_8                      7
#define GLFW_MOUSE_BUTTON_LAST                   GLFW_MOUSE_BUTTON_8
#define GLFW_MOUSE_BUTTON_LEFT                   GLFW_MOUSE_BUTTON_1
#define GLFW_MOUSE_BUTTON_MIDDLE                 GLFW_MOUSE_BUTTON_3
#define GLFW_MOUSE_BUTTON_RIGHT                  GLFW_MOUSE_BUTTON_2

// ---- joystick and hat tokens ----
#define GLFW_HAT_CENTERED                        0
#define GLFW_HAT_DOWN                            4
#define GLFW_HAT_LEFT                            8
#define GLFW_HAT_LEFT_DOWN                       (GLFW_HAT_LEFT  | GLFW_HAT_DOWN)
#define GLFW_HAT_LEFT_UP                         (GLFW_HAT_LEFT  | GLFW_HAT_UP)
#define GLFW_HAT_RIGHT                           2
#define GLFW_HAT_RIGHT_DOWN                      (GLFW_HAT_RIGHT | GLFW_HAT_DOWN)
#define GLFW_HAT_RIGHT_UP                        (GLFW_HAT_RIGHT | GLFW_HAT_UP)
#define GLFW_HAT_UP                              1
#define GLFW_JOYSTICK_1                          0
#define GLFW_JOYSTICK_10                         9
#define GLFW_JOYSTICK_11                         10
#define GLFW_JOYSTICK_12                         11
#define GLFW_JOYSTICK_13                         12
#define GLFW_JOYSTICK_14                         13
#define GLFW_JOYSTICK_15                         14
#define GLFW_JOYSTICK_16                         15
#define GLFW_JOYSTICK_2                          1
#define GLFW_JOYSTICK_3                          2
#define GLFW_JOYSTICK_4                          3
#define GLFW_JOYSTICK_5                          4
#define GLFW_JOYSTICK_6                          5
#define GLFW_JOYSTICK_7                          6
#define GLFW_JOYSTICK_8                          7
#define GLFW_JOYSTICK_9                          8
#define GLFW_JOYSTICK_HAT_BUTTONS                0x00050001
#define GLFW_JOYSTICK_LAST                       GLFW_JOYSTICK_16

// ---- gamepad tokens ----
#define GLFW_GAMEPAD_AXIS_LAST                   GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER
#define GLFW_GAMEPAD_AXIS_LEFT_TRIGGER           4
#define GLFW_GAMEPAD_AXIS_LEFT_X                 0
#define GLFW_GAMEPAD_AXIS_LEFT_Y                 1
#define GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER          5
#define GLFW_GAMEPAD_AXIS_RIGHT_X                2
#define GLFW_GAMEPAD_AXIS_RIGHT_Y                3
#define GLFW_GAMEPAD_BUTTON_A                    0
#define GLFW_GAMEPAD_BUTTON_B                    1
#define GLFW_GAMEPAD_BUTTON_BACK                 6
#define GLFW_GAMEPAD_BUTTON_CIRCLE               GLFW_GAMEPAD_BUTTON_B
#define GLFW_GAMEPAD_BUTTON_CROSS                GLFW_GAMEPAD_BUTTON_A
#define GLFW_GAMEPAD_BUTTON_DPAD_DOWN            13
#define GLFW_GAMEPAD_BUTTON_DPAD_LEFT            14
#define GLFW_GAMEPAD_BUTTON_DPAD_RIGHT           12
#define GLFW_GAMEPAD_BUTTON_DPAD_UP              11
#define GLFW_GAMEPAD_BUTTON_GUIDE                8
#define GLFW_GAMEPAD_BUTTON_LAST                 GLFW_GAMEPAD_BUTTON_DPAD_LEFT
#define GLFW_GAMEPAD_BUTTON_LEFT_BUMPER          4
#define GLFW_GAMEPAD_BUTTON_LEFT_THUMB           9
#define GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER         5
#define GLFW_GAMEPAD_BUTTON_RIGHT_THUMB          10
#define GLFW_GAMEPAD_BUTTON_SQUARE               GLFW_GAMEPAD_BUTTON_X
#define GLFW_GAMEPAD_BUTTON_START                7
#define GLFW_GAMEPAD_BUTTON_TRIANGLE             GLFW_GAMEPAD_BUTTON_Y
#define GLFW_GAMEPAD_BUTTON_X                    2
#define GLFW_GAMEPAD_BUTTON_Y                    3

// ---- error codes ----
#define GLFW_API_UNAVAILABLE                     0x00010006
#define GLFW_FEATURE_UNAVAILABLE                 0x0001000C
#define GLFW_FEATURE_UNIMPLEMENTED               0x0001000D
#define GLFW_FORMAT_UNAVAILABLE                  0x00010009
#define GLFW_INVALID_ENUM                        0x00010003
#define GLFW_INVALID_VALUE                       0x00010004
#define GLFW_NOT_INITIALIZED                     0x00010001
#define GLFW_NO_CURRENT_CONTEXT                  0x00010002
#define GLFW_NO_ERROR                            0
#define GLFW_NO_WINDOW_CONTEXT                   0x0001000A
#define GLFW_OUT_OF_MEMORY                       0x00010005
#define GLFW_VERSION_UNAVAILABLE                 0x00010007

// ---- platform identifiers ----

// ---- other tokens ----
#define GLFW_ACCUM_ALPHA_BITS                    0x0002100A
#define GLFW_ACCUM_BLUE_BITS                     0x00021009
#define GLFW_ACCUM_GREEN_BITS                    0x00021008
#define GLFW_ACCUM_RED_BITS                      0x00021007
#define GLFW_ANY_PLATFORM                        0x00060000
#define GLFW_ANY_POSITION                        0x80000000
#define GLFW_ANY_RELEASE_BEHAVIOR                0
#define GLFW_ARROW_CURSOR                        0x00036001
#define GLFW_CONNECTED                           0x00040001
#define GLFW_CROSSHAIR_CURSOR                    0x00036003
#define GLFW_DISCONNECTED                        0x00040002
#define GLFW_DONT_CARE                           -1
#define GLFW_EGL_CONTEXT_API                     0x00036002
#define GLFW_FLOATING                            0x00020007
#define GLFW_HAND_CURSOR                         GLFW_POINTING_HAND_CURSOR
#define GLFW_HOVERED                             0x0002000B
#define GLFW_HRESIZE_CURSOR                      GLFW_RESIZE_EW_CURSOR
#define GLFW_IBEAM_CURSOR                        0x00036002
#define GLFW_ICONIFIED                           0x00020002
#define GLFW_LOSE_CONTEXT_ON_RESET               0x00031002
#define GLFW_MOUSE_PASSTHROUGH                   0x0002000D
#define GLFW_NATIVE_CONTEXT_API                  0x00036001
#define GLFW_NOT_ALLOWED_CURSOR                  0x0003600A
#define GLFW_NO_API                              0
#define GLFW_NO_RESET_NOTIFICATION               0x00031001
#define GLFW_NO_ROBUSTNESS                       0
#define GLFW_POINTING_HAND_CURSOR                0x00036004
#define GLFW_POSITION_X                          0x0002000E
#define GLFW_POSITION_Y                          0x0002000F
#define GLFW_REFRESH_RATE                        0x0002100F
#define GLFW_RELEASE_BEHAVIOR_FLUSH              0x00035001
#define GLFW_RELEASE_BEHAVIOR_NONE               0x00035002
#define GLFW_RESIZE_ALL_CURSOR                   0x00036009
#define GLFW_RESIZE_EW_CURSOR                    0x00036005
#define GLFW_RESIZE_NESW_CURSOR                  0x00036008
#define GLFW_RESIZE_NS_CURSOR                    0x00036006
#define GLFW_RESIZE_NWSE_CURSOR                  0x00036007
#define GLFW_SRGB_CAPABLE                        0x0002100E
#define GLFW_STEREO                              0x0002100C
#define GLFW_UNLIMITED_MOUSE_BUTTONS             0x00033006
#define GLFW_VRESIZE_CURSOR                      GLFW_RESIZE_NS_CURSOR

// ---- types ----
typedef void (*GLFWglproc)(void);
typedef void (*GLFWvkproc)(void);
typedef struct GLFWmonitor GLFWmonitor;
typedef struct GLFWwindow GLFWwindow;
typedef struct GLFWcursor GLFWcursor;
typedef struct GLFWvidmode
{
 /*! The width, in screen coordinates, of the video mode.
 */
 int width;
 /*! The height, in screen coordinates, of the video mode.
 */
 int height;
 /*! The bit depth of the red channel of the video mode.
 */
 int redBits;
 /*! The bit depth of the green channel of the video mode.
 */
 int greenBits;
 /*! The bit depth of the blue channel of the video mode.
 */
 int blueBits;
 /*! The refresh rate, in Hz, of the video mode.
 */
 int refreshRate;
} GLFWvidmode;
typedef struct GLFWgammaramp
{
 /*! An array of value describing the response of the red channel.
 */
 unsigned short* red;
 /*! An array of value describing the response of the green channel.
 */
 unsigned short* green;
 /*! An array of value describing the response of the blue channel.
 */
 unsigned short* blue;
 /*! The number of elements in each array.
 */
 unsigned int size;
} GLFWgammaramp;
typedef struct GLFWimage
{
 /*! The width, in pixels, of this image.
 */
 int width;
 /*! The height, in pixels, of this image.
 */
 int height;
 /*! The pixel data of this image, arranged left-to-right, top-to-bottom.
 */
 unsigned char* pixels;
} GLFWimage;
typedef struct GLFWgamepadstate
{
 /*! The states of each [gamepad button](@ref gamepad_buttons), `GLFW_PRESS`
 * or `GLFW_RELEASE`.
 */
 unsigned char buttons[15];
 /*! The states of each [gamepad axis](@ref gamepad_axes), in the range -1.0
 * to 1.0 inclusive.
 */
 float axes[6];
} GLFWgamepadstate;
typedef void (* GLFWerrorfun)(int error_code, const char* description);
typedef void (* GLFWwindowposfun)(GLFWwindow* window, int xpos, int ypos);
typedef void (* GLFWwindowsizefun)(GLFWwindow* window, int width, int height);
typedef void (* GLFWwindowclosefun)(GLFWwindow* window);
typedef void (* GLFWwindowrefreshfun)(GLFWwindow* window);
typedef void (* GLFWwindowfocusfun)(GLFWwindow* window, int focused);
typedef void (* GLFWwindowiconifyfun)(GLFWwindow* window, int iconified);
typedef void (* GLFWwindowmaximizefun)(GLFWwindow* window, int maximized);
typedef void (* GLFWframebuffersizefun)(GLFWwindow* window, int width, int height);
typedef void (* GLFWwindowcontentscalefun)(GLFWwindow* window, float xscale, float yscale);
typedef void (* GLFWmousebuttonfun)(GLFWwindow* window, int button, int action, int mods);
typedef void (* GLFWcursorposfun)(GLFWwindow* window, double xpos, double ypos);
typedef void (* GLFWcursorenterfun)(GLFWwindow* window, int entered);
typedef void (* GLFWscrollfun)(GLFWwindow* window, double xoffset, double yoffset);
typedef void (* GLFWkeyfun)(GLFWwindow* window, int key, int scancode, int action, int mods);
typedef void (* GLFWcharfun)(GLFWwindow* window, unsigned int codepoint);
typedef void (* GLFWcharmodsfun)(GLFWwindow* window, unsigned int codepoint, int mods);
typedef void (* GLFWmonitorfun)(GLFWmonitor* monitor, int event);
typedef void (* GLFWjoystickfun)(int jid, int event);

// ---- functions ----
// Only the subset modules/v4d/third/glfw-android implements.
// Anything else is deliberately absent, so using an unsupported
// function is a compile error at the call site rather than a link
// error discovered later.
int             glfwInit(void);
void            glfwTerminate(void);
void            glfwInitHint(int hint, int value);
void            glfwGetVersion(int* major, int* minor, int* rev);
int             glfwGetError(const char** description);
GLFWerrorfun    glfwSetErrorCallback(GLFWerrorfun callback);
int             glfwGetPlatform(void);
int             glfwPlatformSupported(int platform);
void            glfwGetMonitors(GLFWmonitor** monitors, int* count);
GLFWmonitor*    glfwGetPrimaryMonitor(void);
void            glfwGetMonitorPos(GLFWmonitor* monitor, int* xpos, int* ypos);
void            glfwGetMonitorWorkarea(GLFWmonitor* monitor, int* xpos, int* ypos, int* width, int* height);
void            glfwGetMonitorPhysicalSize(GLFWmonitor* monitor, int* widthMM, int* heightMM);
void            glfwGetMonitorContentScale(GLFWmonitor* monitor, float* xscale, float* yscale);
void            glfwSetMonitorUserPointer(GLFWmonitor* monitor, void* pointer);
void*           glfwGetMonitorUserPointer(GLFWmonitor* monitor);
void            glfwSetMonitorCallback(GLFWmonitorfun callback);
const GLFWvidmode* glfwGetVideoModes(GLFWmonitor* monitor, int* count);
const GLFWvidmode* glfwGetVideoMode(GLFWmonitor* monitor);
GLFWwindow*     glfwCreateWindow(int width, int height, const char* title, GLFWmonitor* monitor, GLFWwindow* share);
void            glfwDestroyWindow(GLFWwindow* window);
void            glfwShowWindow(GLFWwindow* window);
void            glfwHideWindow(GLFWwindow* window);
void            glfwIconifyWindow(GLFWwindow* window);
void            glfwRestoreWindow(GLFWwindow* window);
void            glfwMaximizeWindow(GLFWwindow* window);
int             glfwWindowShouldClose(GLFWwindow* window);
void            glfwSetWindowShouldClose(GLFWwindow* window, int value);
void            glfwSetWindowUserPointer(GLFWwindow* window, void* pointer);
void*           glfwGetWindowUserPointer(GLFWwindow* window);
void            glfwSetWindowTitle(GLFWwindow* window, const char* title);
void            glfwSetWindowPos(GLFWwindow* window, int xpos, int ypos);
void            glfwGetWindowPos(GLFWwindow* window, int* xpos, int* ypos);
void            glfwSetWindowSize(GLFWwindow* window, int width, int height);
void            glfwGetWindowSize(GLFWwindow* window, int* width, int* height);
void            glfwGetFramebufferSize(GLFWwindow* window, int* width, int* height);
void            glfwGetWindowContentScale(GLFWwindow* window, float* xscale, float* yscale);
void            glfwGetWindowFrameSize(GLFWwindow* window, int* left, int* top, int* right, int* bottom);
void            glfwSetWindowSizeLimits(GLFWwindow* window, int minwidth, int minheight, int maxwidth, int maxheight);
void            glfwSetWindowAspectRatio(GLFWwindow* window, float numer, float denom);
void            glfwGetWindowAspectRatio(GLFWwindow* window, float* numer, float* denom);
void            glfwSetWindowMonitor(GLFWwindow* window, GLFWmonitor* monitor, int xpos, int ypos, int width, int height, int refreshRate);
GLFWmonitor*    glfwGetWindowMonitor(GLFWwindow* window);
void            glfwSetWindowIcon(GLFWwindow* window, int imageCount, const GLFWimage* images);
void            glfwSetWindowAttrib(GLFWwindow* window, int attrib, int value);
int             glfwGetWindowAttrib(GLFWwindow* window, int attrib);
void            glfwSetWindowPosCallback(GLFWwindow* window, GLFWwindowposfun callback);
void            glfwSetWindowSizeCallback(GLFWwindow* window, GLFWwindowsizefun callback);
void            glfwSetWindowCloseCallback(GLFWwindow* window, GLFWwindowclosefun callback);
void            glfwSetWindowRefreshCallback(GLFWwindow* window, GLFWwindowrefreshfun callback);
void            glfwSetWindowFocusCallback(GLFWwindow* window, GLFWwindowfocusfun callback);
void            glfwSetWindowIconifyCallback(GLFWwindow* window, GLFWwindowiconifyfun callback);
void            glfwSetWindowMaximizeCallback(GLFWwindow* window, GLFWwindowmaximizefun callback);
void            glfwSetFramebufferSizeCallback(GLFWwindow* window, GLFWframebuffersizefun callback);
void            glfwSetWindowContentScaleCallback(GLFWwindow* window, GLFWwindowcontentscalefun callback);
void            glfwPollEvents(void);
void            glfwWaitEvents(void);
void            glfwWaitEventsTimeout(double timeout);
void            glfwPostEmptyEvent(void);
int             glfwGetKey(GLFWwindow* window, int key);
int             glfwGetKeyScancode(int key);
int             glfwGetMouseButton(GLFWwindow* window, int button);
void            glfwGetCursorPos(GLFWwindow* window, double* xpos, double* ypos);
void            glfwSetCursorPos(GLFWwindow* window, double xpos, double ypos);
const char*     glfwGetKeyName(int key, int scancode);
int             glfwGetInputMode(GLFWwindow* window, int mode);
void            glfwSetInputMode(GLFWwindow* window, int mode, int value);
int             glfwRawMouseMotionSupported(void);
void            glfwGetRawMouseMotion(double* xpos, double* ypos);
char**          glfwGetClipboardString(GLFWwindow* window);
void            glfwSetClipboardString(GLFWwindow* window, const char* string);
void            glfwFreeUserPointer(void* pointer);
void            glfwSetKeyCallback(GLFWwindow* window, GLFWkeyfun callback);
void            glfwSetCharCallback(GLFWwindow* window, GLFWcharfun callback);
void            glfwSetCharModsCallback(GLFWwindow* window, GLFWcharmodsfun callback);
void            glfwSetMouseButtonCallback(GLFWwindow* window, GLFWmousebuttonfun callback);
void            glfwSetCursorPosCallback(GLFWwindow* window, GLFWcursorposfun callback);
void            glfwSetCursorEnterCallback(GLFWwindow* window, GLFWcursorenterfun callback);
void            glfwSetScrollCallback(GLFWwindow* window, GLFWscrollfun callback);
void            glfwSetJoystickCallback(GLFWjoystickfun callback);
int             glfwJoystickPresent(int jid);
int             glfwJoystickIsGamepad(int jid);
const float*         glfwGetJoystickAxes(int jid, int* count);
const unsigned char* glfwGetJoystickButtons(int jid, int* count);
const unsigned char* glfwGetJoystickHats(int jid, int* count);
const char*          glfwGetJoystickName(int jid);
const char*          glfwGetGamepadName(int jid);
int             glfwGetGamepadState(int jid, GLFWgamepadstate* state);
void            glfwUpdateGamepadMappings(void);
void            glfwMakeContextCurrent(GLFWwindow* window);
GLFWwindow*     glfwGetCurrentContext(void);
void            glfwSwapBuffers(GLFWwindow* window);
void            glfwSwapInterval(int interval);
GLFWglproc      glfwGetProcAddress(const char* procname);
double          glfwGetTime(void);
void            glfwSetTime(double time);
void            glfwGetTimeValue(double* time);
void            glfwGetDesktopMode(int* width, int* height);
void            glfwGetDesktopModeLimits(int* minWidth, int* minHeight, int* maxWidth, int* maxHeight);
void            glfwGetDesktopModeRefreshRate(int* refreshRate);
void            glfwWindowHint(int hint, int value);
void            glfwDefaultWindowHints(void);

#ifdef __cplusplus
}
#endif

#endif // GLFW_GLFW3_H_
