@startuml
class "nvg::TextRow" as C_0001137271427024381999
class C_0001137271427024381999 {
__
}
class "nvg::GlyphPosition" as C_0004676480056482615399
class C_0004676480056482615399 {
__
}
class "nvg::Paint" as C_0001357020119776512936
class C_0001357020119776512936 {
+Paint() : void
+Paint(const NVGpaint & np) : void
..
+toNVGpaint() : NVGpaint
__
+extent : float[2]
+feather : float
+image : int
+innerColor : cv::Scalar
+outerColor : cv::Scalar
+radius : float
+xform : float[6]
}
class "nvg::detail::NVG" as C_0003149477634212741863
class C_0003149477634212741863 {
-NVG(NVGcontext * ctx) : void
..
+addFallbackFont(const char * baseFont, const char * fallbackFont) : int
+addFallbackFontId(int baseFont, int fallbackFont) : int
+arc(float cx, float cy, float r, float a0, float a1, int dir) : void
+arcTo(float x1, float y1, float x2, float y2, float radius) : void
+beginPath() : void
+bezierTo(float c1x, float c1y, float c2x, float c2y, float x, float y) : void
+boxGradient(float x, float y, float w, float h, float r, float f, const cv::Scalar & icol, const cv::Scalar & ocol) : Paint
+circle(float cx, float cy, float r) : void
+closePath() : void
+createFont(const char * name, const char * filename) : int
+createFontMem(const char * name, unsigned char * data, int ndata, int freeData) : int
+createImage(const char * filename, int imageFlags) : int
+createImageMem(int imageFlags, unsigned char * data, int ndata) : int
+createImageRGBA(int w, int h, int imageFlags, const unsigned char * data) : int
+currentTransform(float * xform) : void
+degToRad(float deg) : float
+deleteImage(int image) : void
+ellipse(float cx, float cy, float rx, float ry) : void
+fill() : void
+fillColor(const cv::Scalar & bgra) : void
+fillPaint(Paint paint) : void
+findFont(const char * name) : int
+fontBlur(float blur) : void
+fontFace(const char * font) : void
+fontFaceId(int font) : void
+fontSize(float size) : void
+getContext() : NVGcontext *
{static} +getCurrentContext() : NVG *
+globalAlpha(float alpha) : void
+imagePattern(float ox, float oy, float ex, float ey, float angle, int image, float alpha) : Paint
+imageSize(int image, int * w, int * h) : void
{static} +initializeContext(NVGcontext * ctx) : void
+intersectScissor(float x, float y, float w, float h) : void
+lineCap(int cap) : void
+lineJoin(int join) : void
+lineTo(float x, float y) : void
+linearGradient(float sx, float sy, float ex, float ey, const cv::Scalar & icol, const cv::Scalar & ocol) : Paint
+miterLimit(float limit) : void
+moveTo(float x, float y) : void
+pathWinding(int dir) : void
+quadTo(float cx, float cy, float x, float y) : void
+radToDeg(float rad) : float
+radialGradient(float cx, float cy, float inr, float outr, const cv::Scalar & icol, const cv::Scalar & ocol) : Paint
+rect(float x, float y, float w, float h) : void
+reset() : void
+resetScissor() : void
+resetTransform() : void
+restore() : void
+rotate(float angle) : void
+roundedRect(float x, float y, float w, float h, float r) : void
+roundedRectVarying(float x, float y, float w, float h, float radTopLeft, float radTopRight, float radBottomRight, float radBottomLeft) : void
+save() : void
+scale(float x, float y) : void
+scissor(float x, float y, float w, float h) : void
+skewX(float angle) : void
+skewY(float angle) : void
+stroke() : void
+strokeColor(const cv::Scalar & bgra) : void
+strokePaint(Paint paint) : void
+strokeWidth(float size) : void
+text(float x, float y, const char * string, const char * end) : float
+textAlign(int align) : void
+textBounds(float x, float y, const char * string, const char * end, float * bounds) : float
+textBox(float x, float y, float breakRowWidth, const char * string, const char * end) : void
+textBoxBounds(float x, float y, float breakRowWidth, const char * string, const char * end, float * bounds) : void
+textBreakLines(const char * string, const char * end, float breakRowWidth, TextRow * rows, int maxRows) : int
+textGlyphPositions(float x, float y, const char * string, const char * end, GlyphPosition * positions, int maxPositions) : int
+textLetterSpacing(float spacing) : void
+textLineHeight(float lineHeight) : void
+textMetrics(float * ascender, float * descender, float * lineh) : void
+transform(float a, float b, float c, float d, float e, float f) : void
+transformIdentity(float * dst) : void
+transformInverse(float * dst, const float * src) : int
+transformMultiply(float * dst, const float * src) : void
+transformPoint(float * dstx, float * dsty, const float * xform, float srcx, float srcy) : void
+transformPremultiply(float * dst, const float * src) : void
+transformRotate(float * dst, float a) : void
+transformScale(float * dst, float sx, float sy) : void
+transformSkewX(float * dst, float a) : void
+transformSkewY(float * dst, float a) : void
+transformTranslate(float * dst, float tx, float ty) : void
+translate(float x, float y) : void
+updateImage(int image, const unsigned char * data) : void
__
-ctx_ : NVGcontext *
{static} -nvg_instance_ : NVG *
}
class "nvg::detail::V4D" as C_0003807488070396424778
class C_0003807488070396424778 {
__
}
class "AllocateFlags" as C_0000417020811991329097
class C_0000417020811991329097 {
__
}
enum "AllocateFlags::Enum" as C_0012501166661497129445
enum C_0012501166661497129445 {
NONE
NANOVG
IMGUI
BGFX
DEFAULT
}
class "ConfigFlags" as C_0014529229705768533980
class C_0014529229705768533980 {
__
}
enum "ConfigFlags::Enum" as C_0002562552376419713783
enum C_0002562552376419713783 {
DEFAULT
OFFSCREEN
DISPLAY_MODE
RESIZEABLE
}
class "DebugFlags" as C_0008758436921973335400
class C_0008758436921973335400 {
__
}
enum "DebugFlags::Enum" as C_0018177560662415004903
enum C_0018177560662415004903 {
DEFAULT
ONSCREEN_CONTEXTS
PRINT_CONTROL_FLOW
DEBUG_GL_CONTEXT
PRINT_LOCK_CONTENTION
MONITOR_RUNTIME_PROPERTIES
LOWER_WORKER_PRIORITY
DONT_PAUSE_LOG
}
class "Source" as C_0018132131310680806956
class C_0018132131310680806956 {
+Source(std::function<bool (cv::UMat &)> generator, float fps) : void
+Source() : void
+~Source() : void
..
+operator()() : cv::UMat
..
+fps() : float
+isOpen() : bool
+isReady() : bool
{static} +make(cv::Ptr<V4D> window, const string & inputFilename) : cv::Ptr<Source>
{static} -makeAnyHWSource(cv::Ptr<V4D> window, const string & inputFilename) : cv::Ptr<Source>
{static} -makeVaSource(cv::Ptr<V4D> window, const string & inputFilename, const int vaDeviceIndex) : cv::Ptr<Source>
__
-fps_ : float
{static} -frame_ : cv::UMat
-generator_ : std::function<bool (cv::UMat &)>
-mtx_ : std::mutex
-open_ : bool
}
class "Sink" as C_0006990402138631853291
class C_0006990402138631853291 {
+Sink(std::function<bool (const uint64_t &,const cv::UMat &)> consumer) : void
+Sink() : void
+~Sink() : void
..
+operator()(const uint64_t & seq, const cv::UMat & frame) : void
..
+isOpen() : bool
+isReady() : bool
{static} +make(cv::Ptr<V4D> window, const string & outputFilename, const float fps, const cv::Size & frameSize) : cv::Ptr<Sink>
{static} +make(cv::Ptr<V4D> window, const string & outputFilename, const float fps, const cv::Size & frameSize, int fourcc) : cv::Ptr<Sink>
{static} -makeAnyHWSink(const string & outputFilename, const int fourcc, const float fps, const cv::Size & frameSize) : cv::Ptr<Sink>
{static} -makeVaSink(cv::Ptr<V4D> window, const string & outputFilename, const int fourcc, const float fps, const cv::Size & frameSize, const int vaDeviceIndex) : cv::Ptr<Sink>
__
-buffer_ : std::map<uint64_t,cv::UMat>
-consumer_ : std::function<bool (const uint64_t &,const cv::UMat &)>
-mtx_ : std::mutex
-nextSeq_ : uint64_t
-open_ : bool
}
class "Value" as C_0004006184862712160472
class C_0004006184862712160472 {
+Value(const bool & read = false) : void
..
+operator=(const any & rhs) : any &
+operator=<T>(T && __rhs) : any &
__
+callback_ : std::function<void (Value &)>
+read_ : const bool
}
class "AnyPropertyMap<K>" as C_0013886943894949195839
class C_0013886943894949195839 {
+AnyPropertyMap() : void
..
+apply<V>(K key, std::function<V (V &)> func) : auto
-check_value_type<V>() constexpr const : void
-check_write(K key) : void
+create<_Bool Tread,V>(K key, const V & value, std::function<void (const V &)> cb) : void
+empty() const : const bool
+get<V>(K key) constexpr const : const V &
+ptr<V>(K key) constexpr const : const V *
+set<V>(K key, const V & value, bool fire = true) : void
+size() const : const size_t
__
-properties_ : std::vector<Value>
}
class "ThreadSafeAnyMap<K>" as C_0003662102418410532648
class C_0003662102418410532648 {
+apply<V>(K key, std::function<V (V &)> func) : V
+create<_Bool Tread,V>(K key, const V & value, const std::function<void (const V &)> & cb = std::function<void(const V& val)>()) : void
+get<V>(K key) : const V &
+ptr<V>(K key) const : V *
+set<V>(K key, const V & value, bool fire = true) : void
__
-mtx_ : std::mutex
}
class "SharedVariables" as C_0016042050790233101354
class C_0016042050790233101354 {
+checkShared<Tplan,T,_Bool Tcheck=true>(Tplan & plan, const T & candidate) : _Bool
{static} +copy(const cv::UMat & from, cv::UMat & to) : void
{static} +copy<T>(const T & from, T & to) : void
{static} +copy<T>(const T & from) : T
{static} +copy_construct<T>(const T & t) : T
-findSharedParent<T>(const T & shared) : std::pair<size_t, size_t>
+getMutexPtr<T>(const T & shared, bool check = true) : std::mutex *
{static} +isPlanMember<Tplan,Tvar>(Tplan & plan, Tvar & var) : _Bool
+lock<T>(const T & shared) : void
+makeSharedVar<T>(const T & candidate) : void
+registerSafe<T>(const T & safe) : void
+safe_copy<T>(const T & from, T & to) : void
{static} +safe_copy<T>(const T & from) : T
+tryLock<T>(const T & shared) : _Bool
+unlock<T>(const T & shared) : void
__
-safeVarsMtx_ : std::mutex
-safeVars_ : std::map<size_t,std::pair<size_t,cv::Ptr<std::mutex>>>
-sharedVarsMtx_ : std::mutex
-sharedVars_ : std::map<size_t,std::pair<size_t,cv::Ptr<std::mutex>>>
}
class "GlobalState" as C_0004515473887012004118
class C_0004515473887012004118 {
{static} +apply<V>(Keys::Enum k, std::function<V (V &)> f) : V
{static} +countNodeLocks() : size_t
{static} +create<_Bool Tread,V>(Keys::Enum k, V v, const std::function<void (const V &)> & cb = std::function<void(const V& val)>()) : void
{static} +get<V>(Keys::Enum k) : const auto &
{static} -getNodeLockInternal(const string & name, const bool owned = true) : cv::Ptr<std::mutex>
{static} +init_keys() : void
{static} -invalidateNodeLockInternal(const string & name) : bool
{static} +isFirstRun() : bool
{static} +isMain() : bool
{static} +lockNode(const string & name) : bool
{static} +once(string name) : bool
{static} +set<V>(Keys::Enum k, V v) : void
{static} +setMainID(const std::thread::id & id) : void
{static} +shared_vars() : SharedVariables &
{static} +tryGetNodeLock(const string & name) : cv::Ptr<std::mutex>
{static} +tryUnlockNode(const string & name) : bool
__
{static} -defaultThreadID_ : const std::thread::id
{static} -isFirstRun_ : bool
{static} -mainThreadID_ : std::thread::id
{static} -map_ : ThreadSafeAnyMap<Keys::Enum>
{static} -nodeLockMap_ : std::map<string,std::pair<std::thread::id,cv::Ptr<std::mutex>>>
{static} -nodeLockMtx_ : std::mutex
{static} -once_ : std::set<string>
{static} -sharedVars_ : SharedVariables
{static} -threadIDMtx_ : std::mutex
}
class "GlobalState::Keys" as C_0013083063126670975516
class C_0013083063126670975516 {
__
}
enum "GlobalState::Keys::Enum" as C_0004958470706845397576
enum C_0004958470706845397576 {
FRAME_CNT
CAPTURE_CNT
FPS_CNT
RUN_CNT
START_TIME
FPS
WORKERS_READY
WORKERS_STARTED
LOCKING
DISPLAY_READY
LOCK_CONTENTION_CNT
LOCK_CONTENTION_RATE
LCR_CNT
SHOW_GUI
TIME_TRACKER
}
class "LocalState" as C_0014179645252067049637
class C_0014179645252067049637 {
{static} +apply<V>(Keys::Enum k, std::function<V (V &)> f) : V
{static} +create<_Bool Tread,V>(Keys::Enum k, V v, const std::function<void (const V &)> & cb = std::function<void(const V& val)>()) : void
{static} +get<V>(Keys::Enum k) : const V &
{static} +init_keys() : void
{static} +set<V>(Keys::Enum k, V v) : void
__
{static} -map_ : ThreadSafeAnyMap<Keys::Enum>
}
class "LocalState::Keys" as C_0006815822484723229865
class C_0006815822484723229865 {
__
}
enum "LocalState::Keys::Enum" as C_0009247281544862909170
enum C_0009247281544862909170 {
WORKER_INDEX
}
class "::gwe::point_traits<P>" as C_0015119817487928403243
class C_0015119817487928403243 {
{static} +make(double x, double y) : P
{static} +set(P & p, double nx, double ny) : void
{static} +sub(const P & a, const P & b) : P
{static} +x(const P & p) : double
{static} +y(const P & p) : double
__
}
class "::gwe::DefaultPoint" as C_0012708610964115047776
class C_0012708610964115047776 {
+DefaultPoint() = default : void
+DefaultPoint(double X, double Y) : void
__
+x : double
+y : double
}
class "::gwe::Event" as C_0016843947279878335601
class C_0016843947279878335601 {
#Event(Class c) : void
+~Event() constexpr = default : void
..
+getClass() const : Class
__
-class_ : Class
}
enum "::gwe::Event::Class" as C_0001265915474608658843
enum C_0001265915474608658843 {
KEYBOARD
MOUSE
JOYSTICK
WINDOW
}
class "::gwe::Keyboard" as C_0006365241362340093307
class C_0006365241362340093307 {
+Keyboard(Type type, Key key) : void
..
+is(Key a) const : bool
+is(Type t) const : bool
+key() const : Key
+type() const : Type
__
-key_ : Key
-type_ : Type
}
enum "::gwe::Keyboard::Key" as C_0013177150707545070116
enum C_0013177150707545070116 {
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
N0
N1
N2
N3
N4
N5
N6
N7
N8
N9
SPACE
ENTER
BACKSPACE
TAB
ESCAPE
UP
DOWN
LEFT
RIGHT
HOME
END
PAGE_UP
PAGE_DOWN
INSERT
DELETE
F1
F2
F3
F4
F5
F6
F7
F8
F9
F10
F11
F12
APOSTROPHE
COMMA
MINUS
PERIOD
SLASH
SEMICOLON
EQUAL
LEFT_BRACKET
BACKSLASH
RIGHT_BRACKET
GRAVE_ACCENT
WORLD_1
WORLD_2
CAPS_LOCK
SCROLL_LOCK
NUM_LOCK
PRINT_SCREEN
PAUSE
F13
F14
F15
F16
F17
F18
F19
F20
F21
F22
F23
F24
F25
KP_0
KP_1
KP_2
KP_3
KP_4
KP_5
KP_6
KP_7
KP_8
KP_9
KP_DECIMAL
KP_DIVIDE
KP_MULTIPLY
KP_SUBTRACT
KP_ADD
KP_ENTER
KP_EQUAL
LEFT_SHIFT
LEFT_CONTROL
LEFT_ALT
LEFT_SUPER
RIGHT_SHIFT
RIGHT_CONTROL
RIGHT_ALT
RIGHT_SUPER
MENU
}
enum "::gwe::Keyboard::Type" as C_0016866077654777490343
enum C_0016866077654777490343 {
PRESS
RELEASE
REPEAT
HOLD
}
class "::gwe::Mouse_<Tpoint>" as C_0002041769044632445656
class C_0002041769044632445656 {
+Mouse_(Type type, Tpoint position) : void
+Mouse_(Type type, Tpoint position, Tpoint data) : void
+Mouse_(Type type, Button button, Tpoint position) : void
+Mouse_(Type type, Button button, Tpoint position, Tpoint data) : void
..
+button() const : Button
+data() const : Tpoint
+is(Button a) const : bool
+is(Type t) const : bool
+position() const : Tpoint
+type() const : Type
__
-button_ : Button
-data_ : Tpoint
-position_ : Tpoint
-type_ : Type
}
enum "::gwe::Mouse_::Button" as C_0000532773679192200195
enum C_0000532773679192200195 {
NO_BUTTON
LEFT
RIGHT
MIDDLE
N4
N5
N6
N7
N8
}
enum "::gwe::Mouse_::Type" as C_0009733855070126646034
enum C_0009733855070126646034 {
PRESS
RELEASE
MOVE
SCROLL
DRAG
HOVER_ENTER
HOVER_EXIT
DOUBLE_CLICK
}
class "::gwe::Joystick" as C_0007382232996547654935
class C_0007382232996547654935 {
+Joystick(Type type, int joystick, Button button) : void
+Joystick(int joystick, Axis axis, float init, float value, float delta) : void
..
+abs() const : float
+active() const : bool
+axis() const : Axis
+button() const : Button
+delta() const : float
+init() const : float
+is(Button a) const : bool
+is(Axis a) const : bool
+is(Type t) const : bool
+joystick() const : int
+state() const : bool
+type() const : Type
+value() const : float
__
-axis_ : Axis
-button_ : Button
-delta_ : float
-init_ : float
-joystick_ : int
-state_ : bool
-type_ : Type
-value_ : float
}
enum "::gwe::Joystick::Type" as C_0000374168703445559807
enum C_0000374168703445559807 {
PRESS
RELEASE
REPEAT
MOVE
}
enum "::gwe::Joystick::Button" as C_0006061297693645892714
enum C_0006061297693645892714 {
NO_BUTTON
A
B
X
Y
LB
RB
BACK
START
GUIDE
LEFT_THUMB
RIGHT_THUMB
DPAD_UP
DPAD_RIGHT
DPAD_DOWN
DPAD_LEFT
}
enum "::gwe::Joystick::Axis" as C_0002489878926223334229
enum C_0002489878926223334229 {
NO_AXIS
LEFT_X
LEFT_Y
RIGHT_X
RIGHT_Y
LEFT_TRIGGER
RIGHT_TRIGGER
}
class "::gwe::Window_<Tpoint>" as C_0002888831577043340027
class C_0002888831577043340027 {
+Window_(Type type, Tpoint data) : void
+Window_(Type type) : void
..
+data() const : Tpoint
+type() const : Type
__
-data_ : Tpoint
-type_ : Type
}
enum "::gwe::Window_::Type" as C_0003425772206774371927
enum C_0003425772206774371927 {
RESIZE
MOVE
FOCUS
UNFOCUS
CLOSE
}
class "::gwe::detail::Holder" as C_0012729458468029756714
class C_0012729458468029756714 {
__
{static} +cursorEnterCallback : CursorEnterCallback
{static} +cursorPosCallback : CursorPosCallback
{static} +keyboardCallback : KeyCallback
{static} +main_window : GLFWwindow *
{static} +mouseButtonCallback : MouseButtonCallback
{static} +queue_vector : std::vector<EventQueue *>
{static} +scrollCallback : ScrollCallback
{static} +windowCloseCallback : WindowCloseCallback
{static} +windowFocusCallback : WindowFocusCallback
{static} +windowPosCallback : WindowPosCallback
{static} +windowSizeCallback : WindowSizeCallback
{static} +window_size : std::pair<int,int>
}
class "::gwe::detail::EventQueue" as C_0010649917465177150647
class C_0010649917465177150647 {
+EventQueue() : void
..
+capacity() const : size_t
-clear_() : void
+consume<Tevent>() : _Bool
+consume<Tevent,Tfn>(Tfn fn) : _Bool
+empty() : bool
+fetch<Tevent>() : std::vector<std::shared_ptr<Tevent> >
+fetch<Tevent,Tfn>(Tfn fn) : std::vector<std::shared_ptr<Tevent> >
+push(const std::shared_ptr<Event> & event) : void
+set_capacity(size_t c) : void
__
-capacity_ : size_t
-mutex_ : std::mutex
}
class "V4D" as C_0009241642393539394913
class C_0009241642393539394913 {
-V4D(const V4D & v4d, const string & title) : void
-V4D(const cv::Rect & size, cv::Size fbsize, const string & title, AllocateFlags::Enum allocFlags, ConfigFlags::Enum confFlags, DebugFlags::Enum debFlags, int samples) : void
+~V4D() : void
..
+allocateFlags() : AllocateFlags::Enum
{static} +apply<V>(Keys::Enum k, std::function<V (V &)> f) : V
#bgfxCtx() : cv::Ptr<BgfxContext>
+configFlags() : ConfigFlags::Enum
+copyFrom(const cv::UMat & arr) : void
+copyTo(cv::UMat & arr) : void
{static} +create<_Bool Tread,Tval>(Keys::Enum key, const Tval & val, const std::function<void (const Tval &)> & cb = std::function<void(const Tval& val)>()) : void
+debugFlags() : DebugFlags::Enum
-display() : bool
#extCtx(int32_t idx = 0) : cv::Ptr<ExtContext>
#fbCtx() const : cv::Ptr<FrameBufferContext>
{static} +get<Tval>(Keys::Enum key) : const auto &
#getGLFWWindow() const : GLFWwindow *
+getPrintFPS() : bool
+getShowFPS() : bool
+getShowTracking() : bool
+getSink() : cv::Ptr<Sink>
+getSource() : cv::Ptr<Source>
#glCtx(int32_t idx = 0) : cv::Ptr<GLContext>
#hasBgfxCtx() : bool
#hasExtCtx(uint32_t idx = 0) : bool
#hasFbCtx() : bool
#hasGlCtx(uint32_t idx = 0) : bool
#hasImguiCtx() : bool
#hasNvgCtx() : bool
#hasPlainCtx() : bool
+hasSink() const : bool
#hasSinkCtx() : bool
+hasSource() const : bool
#hasSourceCtx() : bool
#imguiCtx() : cv::Ptr<ImGuiContextImpl>
{static} +init(const V4D & v4d, const string & title) : cv::Ptr<V4D>
{static} +init(const cv::Rect & viewport, const string & title, AllocateFlags::Enum allocateFlags = AllocateFlags::DEFAULT, ConfigFlags::Enum configFlags = ConfigFlags::DEFAULT, DebugFlags::Enum debugFlags = DebugFlags::DEFAULT, int samples = 0) : cv::Ptr<V4D>
{static} +init(const cv::Rect & viewport, const cv::Size & fbsize, const string & title, AllocateFlags::Enum allocateFlags = AllocateFlags::DEFAULT, ConfigFlags::Enum configFlags = ConfigFlags::DEFAULT, DebugFlags::Enum debugFlags = DebugFlags::DEFAULT, int samples = 0) : cv::Ptr<V4D>
{static} +init_keys() : void
{static} +instance() : cv::Ptr<V4D>
#isFocused() : bool
#numExtCtx() : int32_t
#numGlCtx() : int32_t
#nvgCtx() : cv::Ptr<NanoVGContext>
+pixelRatioX() : float
+pixelRatioY() : float
#plainCtx() : cv::Ptr<PlainContext>
+position() : cv::Vec2f
+printSystemInfo() : void
{static} +run(cv::Ptr<V4D> runtime, std::function<void ()> runGraph) : void
{static} +set<Tval>(Keys::Enum key, const Tval & val, bool fire = true) : void
#setFocused(bool f) : void
+setPrintFPS(bool p) : void
+setShowFPS(bool s) : void
+setShowTracking(bool st) : void
+setSink(cv::Ptr<Sink> sink) : void
+setSource(cv::Ptr<Source> src) : void
#sinkCtx() : cv::Ptr<SinkContext>
+size() : const cv::Size &
#sourceCtx() : cv::Ptr<SourceContext>
-swapContextBuffers() : void
+title() const : std::string
__
-allocateFlags_ : AllocateFlags::Enum
-bgfxContext_ : cv::Ptr<BgfxContext>
-closed_ : bool
-configFlags_ : ConfigFlags::Enum
-currentID_ : std::string
-debugFlags_ : DebugFlags::Enum
-extContexts_ : std::map<int32_t,cv::Ptr<ExtContext>>
-glContexts_ : std::map<int32_t,cv::Ptr<GLContext>>
-glCtxMtx_ : std::mutex
-imguiContext_ : cv::Ptr<ImGuiContextImpl>
{static} -instance_ : cv::Ptr<V4D>
{static} -instance_mtx_ : std::mutex
-mainFbContext_ : cv::Ptr<FrameBufferContext>
-nvgContext_ : cv::Ptr<NanoVGContext>
-plainContext_ : cv::Ptr<PlainContext>
-printFPS_ : bool
{static} -properties_ : ThreadSafeAnyMap<Keys::Enum>
-samples_ : int
-showFPS_ : bool
-showTracking_ : bool
-sinkContext_ : cv::Ptr<SinkContext>
-sink_ : cv::Ptr<Sink>
-sourceContext_ : cv::Ptr<SourceContext>
-source_ : cv::Ptr<Source>
}
class "V4D::Keys" as C_0009210610883687851085
class C_0009210610883687851085 {
__
}
enum "V4D::Keys::Enum" as C_0017169443452162644709
enum C_0017169443452162644709 {
SIZE
VIEWPORT
WINDOW_SIZE
FRAMEBUFFER_SIZE
CLEAR_COLOR
NAMESPACE
FULLSCREEN
DISABLE_INPUT_EVENTS
VISIBLE
}
abstract "Plan" as C_0006592830754155008201
abstract C_0006592830754155008201 {
+~Plan() : void
..
+operator()<Edges...>(Edges &&... edges) : auto
..
+AND<Edges...>(Edges &&... edges) : auto
+ASSIGN<Edges...>(Edges &&... edges) : auto
+BAND<Edges...>(Edges &&... edges) : auto
+BOR<Edges...>(Edges &&... edges) : auto
+CS<T>(T & t) : detail::Edge<T, true, true, true>
+DECL<Edges...>(Edges &&... edges) : auto
+DECR<Edges...>(Edges &&... edges) : auto
+DIV<Edges...>(Edges &&... edges) : auto
+E<Tclass>(typename Tclass::Type t) : Event<Tclass>
+E<Tclass>() : Event<Tclass>
+E<Tclass,Ttrigger>(typename Tclass::Type t, Ttrigger tr) : Event<Tclass>
+EQ<Edges...>(Edges &&... edges) : auto
+F<Tfn,Args...>(Tfn src, Args &&... args) : auto
+GE<Edges...>(Edges &&... edges) : auto
+GT<Edges...>(Edges &&... edges) : auto
+IF<Edges...>(Edges &&... edges) : auto
+INCL<Edges...>(Edges &&... edges) : auto
+INCR<Edges...>(Edges &&... edges) : auto
+LE<Edges...>(Edges &&... edges) : auto
+LT<Edges...>(Edges &&... edges) : auto
+MOD<Edges...>(Edges &&... edges) : auto
+MUL<Edges...>(Edges &&... edges) : auto
+NEQ<Edges...>(Edges &&... edges) : auto
+NOT<Edges...>(Edges &&... edges) : auto
+OP<Operators Top,Edges...>(Edges... edges) : auto
+OR<Edges...>(Edges &&... edges) : auto
+P<Tval>(V4D::Keys::Enum key) : Property<Tval>
+P<Tval>(LocalState::Keys::Enum key) : Property<Tval>
+P<Tval>(GlobalState::Keys::Enum key) : Property<Tval>
+R<T>(const T & t) : detail::Edge<T, false, true>
+RS<T>(const T & t) : detail::Edge<T, false, true, true>
+RW<T>(T & t) : detail::Edge<T, false, false>
+RWS<T>(T & t) : detail::Edge<T, false, false, true>
+SHL<Edges...>(Edges &&... edges) : auto
+SHR<Edges...>(Edges &&... edges) : auto
+SUB<Edges...>(Edges &&... edges) : auto
+V<T>(T t) : detail::Edge<cv::Ptr<T>, false, true, false, T, true>
+XOR<Edges...>(Edges &&... edges) : auto
+_<Args...>(Args &&... args) : auto
+_safe<Tvar>(Tvar & val) : void
+_shared<Tvar>(Tvar & val) : void
+_sub<TsubPlan,Tparent,Args...>(Tparent * parent, Args &&... args) : auto
+_sub<TsubPlan,TparentPtr,Args...>(TparentPtr parent, Args &&... args) : auto
-add_transaction<Tfn,Args...>(cv::Ptr<V4DContext> ctx, const string & txID, Tfn fn, Args... args) : void
-add_transaction<Tfn,Args...>(std::function<cv::Ptr<V4DContext> ()> ctxCb, string txID, Tfn fn, Args... args) : void
-add_transaction<Tfn,Args...>(BranchType::Enum btype, cv::Ptr<V4DContext> ctx, const string & txID, Tfn fn, Args... args) : void
-add_transaction<Tfn,Args...>(BranchType::Enum btype, std::function<cv::Ptr<V4DContext> ()> ctxCb, string txID, Tfn fn, Args... args) : void
+assign<Edges...>(Edges... edges) : cv::Ptr<Plan>
+bgfx<Tfn,Args...>(Tfn fn, Args... args) : cv::Ptr<Plan>
+branch<Tfn,Args...>(BranchType::Enum type, Tfn fn, Args... args) : cv::Ptr<Plan>
+branch<Tedge>(Tedge edge) : typename std::enable_if<std::is_base_of_v<EdgeBase, Tedge>, cv::Ptr<Plan> >::type
+branch<Tfn>(Tfn fn) : typename std::enable_if<! std::is_base_of_v<EdgeBase, Tfn>, cv::Ptr<Plan> >::type
+branch<Tfn,Args...>(Tfn fn, Args... args) : typename std::enable_if<! std::is_integral_v<Tfn>, cv::Ptr<Plan> >::type
+branch<Tfn,Args...>(BranchType::Enum type, int workerIdx, Tfn fn, Args... args) : cv::Ptr<Plan>
+branch<Tfn,Args...>(int workerIdx, Tfn fn, Args... args) : typename std::enable_if<! std::is_base_of<EdgeBase, Tfn>::value, cv::Ptr<Plan> >::type
+branch<Tfn,Args...>(int workerIdx, BranchType::Enum type, Tfn fn, Args... args) : cv::Ptr<Plan>
+branch<Tedge>(BranchType::Enum type, Tedge edge) : typename std::enable_if<std::is_base_of_v<EdgeBase, Tedge>, cv::Ptr<Plan> >::type
+call<Tctx,Tfn,Tuple,size_t... idx>(Tctx ctx, const string & name, Tfn fn, Tuple && args, std::index_sequence<idx...>) : cv::Ptr<Plan>
+capture<Tedge>(Tedge && edge) : cv::Ptr<Plan>
+capture<Tfn,Args...>(Tfn fn, Args... args) : typename std::enable_if<! std::is_base_of_v<EdgeBase, Tfn>, cv::Ptr<Plan> >::type
+capture() : cv::Ptr<Plan>
+clear(const int32_t & glIndex = -1) : cv::Ptr<Plan>
-clearGraph() : void
+construct<Edges...>(Edges... edges) : cv::Ptr<Plan>
+elseBranch() : cv::Ptr<Plan>
-emit_access<Tedge>(const string & context, Tedge tp) : void
+endBranch() : cv::Ptr<Plan>
+ext<int32_t pos=0,Tedge,Tfn,Args...>(Tedge indexEdge, Tfn fn, Args... args) : typename std::enable_if<std::is_base_of<EdgeBase, Tedge>::value, cv::Ptr<Plan> >::type
+ext<Tfn,Args...>(Tfn fn, Args... args) : typename std::enable_if<! std::is_base_of<EdgeBase, Tfn>::value, cv::Ptr<Plan> >::type
+fb<size_t pos=0,Tfn,Args...>(Tfn fn, Args... args) : cv::Ptr<Plan>
-findNode(const string & name, cv::Ptr<Node> & found) : void
-getActualTypeSize() : size_t
-getParentActualTypeSize() : size_t
+getParentID() : std::string
-getParentOffset() : size_t
+gl<Tfn,Args...>(Tfn fn, Args... args) : typename std::enable_if<! std::is_base_of<EdgeBase, Tfn>::value, cv::Ptr<Plan> >::type
+gl<int32_t pos=0,Tedge,Tfn,Args...>(Tedge indexEdge, Tfn fn, Args... args) : typename std::enable_if<std::is_base_of<EdgeBase, Tedge>::value, cv::Ptr<Plan> >::type
+gui() : void
+imgui<Tfn,Args...>(Tfn fn, Args &&... args) : void
{abstract} +infer() = 0 : void
{static} +make<Tplan,Args...>(Args &&... args) : cv::Ptr<Tplan>
-makeGraph() : void
-makeInternalEdge<_Bool Tconst,T>(T & val) : auto
{static} -makeSubPlan<Tplan,Tparent,Args...>(Tparent * parent, Args &&... args) : cv::Ptr<Tplan>
-make_id<Tfn,Args...>(string id, const string & name, Tfn fn, Args... args) : const string
-make_op<_Bool TmakeEdge=true,TfnOp,Args...>(TfnOp fn, Args... args) : auto
+make_setter_function<Tkey,Tfn,Ttuple,size_t... idx>(Tkey key, Tfn fn, Ttuple && args, std::index_sequence<idx...>) : auto
+make_setter_function<Ttuple>(Ttuple && values) : auto
+name() : std::string
+nvg<Tfn,Args...>(Tfn fn, Args... args) : cv::Ptr<Plan>
+op<Operators Top,Edges...>(Edges... edges) : cv::Ptr<Plan>
-pf(const size_t & depth, const BranchState & current, const cv::Ptr<Node> n) : void
+plain<Args...>(Args... args) : cv::Ptr<Plan>
+plain<Tfn,Args...>(Tfn fn, Args... args) : typename std::enable_if<! std::is_base_of<EdgeBase, Tfn>::value, cv::Ptr<Plan> >::type
{static} +run<Tplan,Args...>(int32_t workers, Args &&... args) : void
-runGraph() : void
-self<Tinstance>() : cv::Ptr<Tinstance>
+set<Tedge>(const V4D::Keys::Enum & key, const Tedge & e) : cv::Ptr<Plan>
+set<Args...>(std::tuple<V4D::Keys::Enum,Args> &&... tuples) : cv::Ptr<Plan>
+set<Tedge>(std::tuple<V4D::Keys::Enum,Tedge> && values) : cv::Ptr<Plan>
+set<TwrapFn,Ttuple,size_t... idx>(const string & id, TwrapFn fn, Ttuple && args, std::index_sequence<idx...>) : cv::Ptr<Plan>
+set<Tedge,size_t... idx>(std::tuple<V4D::Keys::Enum,Tedge> && values, std::index_sequence<idx...>) : cv::Ptr<Plan>
-setActualTypeSize<T>() : void
-setParentActualTypeSize<T>() : void
+setParentID(const string & parent) : void
-setParentOffset(size_t offset) : void
+setup() : void
+space() : std::string
+subInfer<TsubPlan>(cv::Ptr<TsubPlan> subPlan) : cv::Ptr<Plan>
+subSetup<TsubPlan>(cv::Ptr<TsubPlan> subPlan) : cv::Ptr<Plan>
+subTeardown<TsubPlan>(cv::Ptr<TsubPlan> subPlan) : cv::Ptr<Plan>
+teardown() : void
+wrapGuiCall<Tfn,Tuple,size_t... idx>(Tfn fn, Tuple && args, std::index_sequence<idx...>) : auto
{static} -wrap_callable<Args...,Tfn>(Tfn fn) : auto
+write<Tfn,Args...>(Tfn fn, Args... args) : typename std::enable_if<! std::is_base_of_v<EdgeBase, Tfn>, cv::Ptr<Plan> >::type
+write<Tedge>(Tedge && edge) : cv::Ptr<Plan>
+write() : cv::Ptr<Plan>
__
-accesses_ : std::vector<std::tuple<std::string,bool,size_t>>
-actualTypeSize_ : size_t
-allNodes_ : std::vector<cv::Ptr<Node>>
{static} +always_ : const Plan::(lambda at /home/elchaschab/devel/Plan-V4D/modules/v4d/include/opencv2/v4d/v4d.hpp:994:34)
{static} +and_ : const Plan::(lambda at /home/elchaschab/devel/Plan-V4D/modules/v4d/include/opencv2/v4d/v4d.hpp:997:31)
-branchStack_ : std::deque<std::pair<string,BranchType::Enum>>
-branchStateStack_ : std::deque<BranchState>
-captureFrame_ : cv::UMat
-currentNodes_ : std::vector<cv::Ptr<Node>>
{static} +isFalse_ : const Plan::(lambda at /home/elchaschab/devel/Plan-V4D/modules/v4d/include/opencv2/v4d/v4d.hpp:996:35)
{static} +isTrue_ : const Plan::(lambda at /home/elchaschab/devel/Plan-V4D/modules/v4d/include/opencv2/v4d/v4d.hpp:995:34)
{static} +or_ : const Plan::(lambda at /home/elchaschab/devel/Plan-V4D/modules/v4d/include/opencv2/v4d/v4d.hpp:998:30)
-parentActualTypeSize_ : size_t
-parentOffset_ : size_t
-parent_ : std::string
-runtime_ : cv::Ptr<V4D>
-self_ : cv::Ptr<Plan>
-transactions_ : std::map<std::string,cv::Ptr<Transaction>>
-writerFrame_ : cv::UMat
}
class "Plan::BranchState" as C_0001505393889902592786
class C_0001505393889902592786 {
__
+branchID_ : string
+condition_ : bool
+isEnabled_ : bool
+isLocked_ : bool
+isOnce_ : bool
+isSingle_ : bool
}
class "Plan::Property<T>" as C_0014692114362314016994
class C_0014692114362314016994 {
+Property(cv::Ptr<Plan> plan, const T & val) : void
__
}
class "Plan::Event<TeventClass,Tfn=std::function<std::vector<std::shared_ptr<TeventClass> > (void)>,Tparent=Edge<Tfn, false, true, false>>" as C_0001651084643576598522
class C_0001651084643576598522 {
+Event(cv::Ptr<Plan> plan) : void
+Event(cv::Ptr<Plan> plan, const typename TeventClass::Type t) : void
+Event<Ttrigger>(cv::Ptr<Plan> plan, const typename TeventClass::Type t, const Ttrigger tr) : void
__
}
C_0003149477634212741863 ..> C_0004676480056482615399
C_0003149477634212741863 ..> C_0001137271427024381999
C_0003149477634212741863 ..> C_0001357020119776512936
C_0003149477634212741863 --> C_0003149477634212741863 : -nvg_instance_
C_0003149477634212741863 <.. C_0003807488070396424778 : +<<friend>>
C_0012501166661497129445 --+ C_0000417020811991329097
C_0002562552376419713783 --+ C_0014529229705768533980
C_0018177560662415004903 --+ C_0008758436921973335400
C_0018132131310680806956 ..> C_0009241642393539394913
C_0006990402138631853291 ..> C_0009241642393539394913
C_0004006184862712160472 --> C_0004006184862712160472 : +callback_
C_0013886943894949195839 o-- C_0004006184862712160472 : -properties_
C_0013886943894949195839 <|-- C_0003662102418410532648
C_0004515473887012004118 --> C_0003662102418410532648 : -map_
C_0004515473887012004118 --> C_0004958470706845397576 : -map_
C_0004515473887012004118 --> C_0016042050790233101354 : -sharedVars_
C_0013083063126670975516 --+ C_0004515473887012004118
C_0004958470706845397576 --+ C_0013083063126670975516
C_0014179645252067049637 --> C_0003662102418410532648 : -map_
C_0014179645252067049637 --> C_0009247281544862909170 : -map_
C_0006815822484723229865 --+ C_0014179645252067049637
C_0009247281544862909170 --+ C_0006815822484723229865
C_0016843947279878335601 o-- C_0001265915474608658843 : -class_
C_0001265915474608658843 --+ C_0016843947279878335601
C_0006365241362340093307 o-- C_0013177150707545070116 : -key_
C_0006365241362340093307 o-- C_0016866077654777490343 : -type_
C_0016843947279878335601 <|-- C_0006365241362340093307
C_0013177150707545070116 --+ C_0006365241362340093307
C_0016866077654777490343 --+ C_0006365241362340093307
C_0002041769044632445656 o-- C_0000532773679192200195 : -button_
C_0002041769044632445656 o-- C_0009733855070126646034 : -type_
C_0016843947279878335601 <|-- C_0002041769044632445656
C_0000532773679192200195 --+ C_0002041769044632445656
C_0009733855070126646034 --+ C_0002041769044632445656
C_0007382232996547654935 o-- C_0000374168703445559807 : -type_
C_0007382232996547654935 o-- C_0006061297693645892714 : -button_
C_0007382232996547654935 o-- C_0002489878926223334229 : -axis_
C_0016843947279878335601 <|-- C_0007382232996547654935
C_0000374168703445559807 --+ C_0007382232996547654935
C_0006061297693645892714 --+ C_0007382232996547654935
C_0002489878926223334229 --+ C_0007382232996547654935
C_0002888831577043340027 o-- C_0003425772206774371927 : -type_
C_0016843947279878335601 <|-- C_0002888831577043340027
C_0003425772206774371927 --+ C_0002888831577043340027
C_0012729458468029756714 --> C_0010649917465177150647 : +queue_vector
C_0010649917465177150647 ..> C_0016843947279878335601
C_0009241642393539394913 o-- C_0012501166661497129445 : -allocateFlags_
C_0009241642393539394913 o-- C_0002562552376419713783 : -configFlags_
C_0009241642393539394913 o-- C_0018177560662415004903 : -debugFlags_
C_0009241642393539394913 o-- C_0018132131310680806956 : -source_
C_0009241642393539394913 o-- C_0006990402138631853291 : -sink_
C_0009241642393539394913 --> C_0009241642393539394913 : -instance_
C_0009241642393539394913 --> C_0003662102418410532648 : -properties_
C_0009241642393539394913 --> C_0017169443452162644709 : -properties_
C_0009241642393539394913 <.. C_0006592830754155008201 : +<<friend>>
C_0009241642393539394913 <.. C_0006990402138631853291 : +<<friend>>
C_0009241642393539394913 <.. C_0018132131310680806956 : +<<friend>>
C_0009210610883687851085 --+ C_0009241642393539394913
C_0017169443452162644709 --+ C_0009210610883687851085
C_0006592830754155008201 ..> C_0001505393889902592786
C_0006592830754155008201 ..> C_0017169443452162644709
C_0006592830754155008201 ..> C_0009247281544862909170
C_0006592830754155008201 ..> C_0004958470706845397576
C_0006592830754155008201 o-- C_0009241642393539394913 : -runtime_
C_0006592830754155008201 o-- C_0006592830754155008201 : -self_
C_0006592830754155008201 <.. C_0016042050790233101354 : +<<friend>>
C_0006592830754155008201 <.. C_0009241642393539394913 : +<<friend>>
C_0001505393889902592786 --+ C_0006592830754155008201
C_0014692114362314016994 --+ C_0006592830754155008201
C_0001651084643576598522 --+ C_0006592830754155008201

'Generated with clang-uml, version 0.6.3-5-g3650837
'LLVM version clang version 18.1.8
@enduml
