// This file is part of OpenCV project.
// It is subject to the license terms in the LICENSE file found in the top-level
// directory of this distribution and at http://opencv.org/license.html.
// Copyright Amir Hassan (kallaballa) <amir@viel-zu.org>
//
// A GLFW-compatible implementation for Android, declared by GLFW/glfw3.h.
//
// GLFW has no Android backend. third/glfw/src/platform.c only knows WIN32,
// COCOA, WAYLAND and X11, so under the NDK toolchain there is no platform for
// glfwInit() to connect to -- and the library does not even configure, because
// its X11/Wayland backends default to ON there and then hard-require X11 headers
// that the sysroot does not ship.
//
// Rather than teach V4D about EGL at every call site, this implements the subset
// of the GLFW API that FrameBufferContext, events.hpp/gwe and the samples use on
// top of EGL + ANativeWindow + AInputQueue. The declarations sit in
// GLFW/glfw3.h next to this file (generated by
// tools/android/gen-glfw-shim-header.py) and shadow the vendored GLFW header on
// the Android include path, so no V4D source needs a #ifdef.
//
// Where the emulation is imperfect it is called out below: Android owns the
// surface, so window management and cursors are stubs, joystick enumeration
// reports nothing, and events are drained on whichever thread calls
// glfwPollEvents() -- the same rule gwe already relies on.

#include <GLFW/glfw3.h>

#if defined(OPENCV_V4D_ANDROID)

#include "glfw_android.hpp"

#include <EGL/egl.h>
#include <EGL/eglext.h>

#include <android/configuration.h>
#include <android/keycodes.h>
#include <android/looper.h>
#include <android/log.h>

#include <algorithm>
#include <chrono>
#include <condition_variable>
#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <mutex>
#include <string>
#include <vector>

#define LOG_TAG "v4d-glfw"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)

namespace {

// Long enough that a slow activity start is not mistaken for a failure, short
// enough that a genuinely surface-less process does not hang forever.
constexpr int64_t kSurfaceWaitNs = 10ll * 1000 * 1000 * 1000;

// The identifier the input queue is attached to under the looper. Any value
// works as long as it cannot collide with the other identifiers in the process;
// the NDK's native_app_glue uses 1 for the same purpose.
constexpr int kInputQueueIdent = 1;

double monotonicSeconds() {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return static_cast<double>(ts.tv_sec) + ts.tv_nsec / 1e9;
}

} // namespace

// ---------------------------------------------------------------------------
// Window and monitor types. Upstream keeps these opaque; here they are real so
// that the callbacks and the input state have somewhere to live.
// ---------------------------------------------------------------------------

struct GLFWmonitor {
  GLFWvidmode mode{};
  int widthMM = 0;
  int heightMM = 0;
  float xscale = 1.f;
  float yscale = 1.f;
  void *userPointer = nullptr;
};

struct GLFWwindow {
  // Surface
  ANativeWindow *nativeWindow = nullptr; // strong: acquired on create, released on destroy
  EGLDisplay display = nullptr;
  EGLSurface surface = nullptr;
  EGLContext context = nullptr;
  EGLConfig config = nullptr;

  // Geometry. Android makes no distinction between points and pixels.
  int width = 0;
  int height = 0;
  int xpos = 0;
  int ypos = 0;
  float xscale = 1.f;
  float yscale = 1.f;

  // State
  bool visible = true;
  bool iconified = false;
  bool focused = true;
  bool resizable = true;
  bool decorated = true;
  bool floating = false;
  bool shouldClose = false;
  int swapInterval = 0;
  void *userPointer = nullptr;
  GLFWmonitor *monitor = nullptr;
  GLFWwindow *share = nullptr;
  int contextVersionMajor = 3;
  int contextVersionMinor = 0;

  // Callbacks
  GLFWwindowposfun posCallback = nullptr;
  GLFWwindowsizefun sizeCallback = nullptr;
  GLFWwindowclosefun closeCallback = nullptr;
  GLFWwindowrefreshfun refreshCallback = nullptr;
  GLFWwindowfocusfun focusCallback = nullptr;
  GLFWwindowiconifyfun iconifyCallback = nullptr;
  GLFWwindowmaximizefun maximizeCallback = nullptr;
  GLFWframebuffersizefun framebufferSizeCallback = nullptr;
  GLFWwindowcontentscalefun contentScaleCallback = nullptr;
  GLFWmousebuttonfun mouseButtonCallback = nullptr;
  GLFWcursorposfun cursorPosCallback = nullptr;
  GLFWcursorenterfun cursorEnterCallback = nullptr;
  GLFWscrollfun scrollCallback = nullptr;
  GLFWkeyfun keyCallback = nullptr;
  GLFWcharfun charCallback = nullptr;
  GLFWcharmodsfun charModsCallback = nullptr;

  // Input state
  unsigned char keys[GLFW_KEY_LAST + 1] = {0};
  unsigned char buttons[GLFW_MOUSE_BUTTON_LAST + 1] = {0};
  double cursorX = 0.0;
  double cursorY = 0.0;
  bool cursorInside = false;

  // There is exactly one surface on Android, so the first window created owns it
  // and receives the input; V4D's offscreen child windows share it.
  bool ownsSurface = false;
};

// ---------------------------------------------------------------------------
// Process-wide state
// ---------------------------------------------------------------------------

namespace {

struct WindowHints {
  int contextVersionMajor = 3;
  int contextVersionMinor = 0;
  int samples = 0;
  // GLFW's own defaults for these; V4D re-hints most of them from the monitor's
  // video mode before every window, but a sample that does not has to get
 // something reasonable rather than the driver's smallest possible config.
  int red = 8;
  int green = 8;
  int blue = 8;
  int alpha = 8;
  int depth = 24;
  int stencil = 8;
  bool resizable = true;
  bool visible = true;
  bool decorated = true;
  bool focused = true;
};

struct Platform {
  // Recursive because reportError() invokes the user callback, and a GLFW error
  // callback that logs through V4D can re-enter the shim.
  std::recursive_mutex mutex;
  std::condition_variable_any surfaceCv;

  ANativeActivity *activity = nullptr;
  AInputQueue *inputQueue = nullptr;
  ALooper *looper = nullptr;
  ANativeWindow *nativeWindow = nullptr; // weak: the activity owns it
  bool resumed = false;
  uint64_t windowGeneration = 1;

  // The one EGL display of the process, initialised on first use and reference
  // counted: eglGetDisplay hands out the same handle every time, and
  // eglTerminate() invalidates every context and surface on it, so tearing the
  // display down with a child window still alive would take that child down too.
  EGLDisplay display = EGL_NO_DISPLAY;
  int displayUsers = 0;
  int eglMajor = 0;
  int eglMinor = 0;
  // The config is display-scoped and expensive to pick, so it is cached together
  // with the hints that produced it.
  EGLConfig config = nullptr;
  WindowHints configHints{};
  bool configValid = false;

  // Display size in pixels, recorded when the activity reports a configuration
  // change. It is what FrameBufferContext asks for before a surface exists.
  int displayWidthPx = 0;
  int displayHeightPx = 0;

  GlfwAndroidInputHandler inputHandler = nullptr;

  bool initialized = false;
  GLFWerrorfun errorCallback = nullptr;
  int lastError = GLFW_NO_ERROR;
  std::string lastErrorText;

  double timeOffset = 0.0;
  GLFWwindow *currentContext = nullptr;
  GLFWmonitor primaryMonitor;
  GLFWmonitorfun monitorCallback = nullptr;
  GLFWjoystickfun joystickCallback = nullptr;
  std::vector<GLFWwindow *> windows;
  WindowHints hints;
};

Platform gPlatform;

Platform &platform() {
  static Platform instance;
  return instance;
}

// Defined at the bottom, next to the desktop-mode queries that need it. It sits
// inside the extern "C" block with the GLFW entry points, so it has to be
// declared here in an extern "C" block too -- a C++-linkage declaration would
// make every call below ambiguous.
extern "C" void refreshDisplayMode();
void reportError(int code, const char *fmt, ...) {
  Platform &p = platform();
  char buffer[512];
  va_list args;
  va_start(args, fmt);
  vsnprintf(buffer, sizeof(buffer), fmt, args);
  va_end(args);
  p.lastError = code;
  p.lastErrorText = buffer;
  LOGW("error %d: %s", code, buffer);
  if (p.errorCallback)
    p.errorCallback(code, buffer);
}

ANativeWindow *acquireWindowLocked() {
  ANativeWindow *window = platform().nativeWindow;
  if (window)
    ANativeWindow_acquire(window);
  return window;
}

/// The size of whatever a window draws into.
///
/// For the window that owns the activity's ANativeWindow that is the surface
/// itself: Android gives an app the whole screen, so a requested size is not one
/// the platform can honour, and reporting it back anyway would leave V4D
/// blitting its framebuffer into a corner of a drawable it believes is a
/// different size. Offscreen children have no surface at all -- they get an
/// offscreen one of exactly the size they asked for, which is what their
/// framebuffers are sized after.
void drawableSize(GLFWwindow *window, int &width, int &height) {
  width = window ? window->width : 0;
  height = window ? window->height : 0;
  if (window && window->ownsSurface && window->nativeWindow) {
    width = ANativeWindow_getWidth(window->nativeWindow);
    height = ANativeWindow_getHeight(window->nativeWindow);
  }
}

/// Reads the drawable size and announces it if it changed -- a rotation, a
/// resize or a foldable unfolding all show up as a different ANativeWindow size
/// with no event of their own. Called from the frame loop
/// (glfwPollEvents/glfwSwapBuffers), and never from a query: FrameBufferContext
/// asks for the size through glfwGetWindowSize()/glfwGetVideoMode() before the
/// first frame, and re-entering the callback chain from there would be wrong.
///
/// This is also how V4D learns the size at all. The window starts out reporting
/// what was asked for, and the first pass through the frame loop replaces it with
/// the surface's real size and fires the framebuffer-size callback, which is what
/// sets the WINDOW_SIZE property the display path blits into.
void updateSizeAndNotify(GLFWwindow *window) {
  if (!window)
    return;
  int width = 0, height = 0;
  drawableSize(window, width, height);
  if (width == window->width && height == window->height)
    return;
  window->width = width;
  window->height = height;
  if (window->framebufferSizeCallback)
    window->framebufferSizeCallback(window, width, height);
  if (window->sizeCallback)
    window->sizeCallback(window, width, height);
}

int glfwModsFromMetaState(int32_t metaState) {
  int mods = 0;
  if (metaState & AMETA_SHIFT_ON)
    mods |= GLFW_MOD_SHIFT;
  if (metaState & AMETA_CTRL_ON)
    mods |= GLFW_MOD_CONTROL;
  if (metaState & AMETA_ALT_ON)
    mods |= GLFW_MOD_ALT;
  if (metaState & AMETA_META_ON)
    mods |= GLFW_MOD_SUPER;
  return mods;
}

// Android and GLFW number keys differently: GLFW uses printable ASCII for
// letters and digits and a dense range for the function keys. Both families are
// contiguous in AKEYCODE and in the GLFW tokens, so they translate by offset;
// everything else needs an explicit pair.
int glfwKeyFromAndroid(int32_t keycode, int32_t source) {
  if (keycode >= AKEYCODE_A && keycode <= AKEYCODE_Z)
    return GLFW_KEY_A + (keycode - AKEYCODE_A);
  if (keycode >= AKEYCODE_0 && keycode <= AKEYCODE_9)
    return GLFW_KEY_0 + (keycode - AKEYCODE_0);
  if (keycode >= AKEYCODE_F1 && keycode <= AKEYCODE_F12)
    return GLFW_KEY_F1 + (keycode - AKEYCODE_F1);
  if (keycode >= AKEYCODE_NUMPAD_0 && keycode <= AKEYCODE_NUMPAD_9)
    return GLFW_KEY_KP_0 + (keycode - AKEYCODE_NUMPAD_0);

  switch (keycode) {
  case AKEYCODE_SPACE: return GLFW_KEY_SPACE;
  case AKEYCODE_ENTER:
    // The numeric keypad's enter is a different GLFW key.
    return (source == AINPUT_SOURCE_KEYBOARD) ? GLFW_KEY_KP_ENTER : GLFW_KEY_ENTER;
  case AKEYCODE_DEL: return GLFW_KEY_BACKSPACE;
  case AKEYCODE_FORWARD_DEL: return GLFW_KEY_DELETE;
  case AKEYCODE_TAB: return GLFW_KEY_TAB;
  case AKEYCODE_ESCAPE: return GLFW_KEY_ESCAPE;
  case AKEYCODE_MINUS: return GLFW_KEY_MINUS;
  case AKEYCODE_EQUALS: return GLFW_KEY_EQUAL;
  case AKEYCODE_LEFT_BRACKET: return GLFW_KEY_LEFT_BRACKET;
  case AKEYCODE_RIGHT_BRACKET: return GLFW_KEY_RIGHT_BRACKET;
  case AKEYCODE_BACKSLASH: return GLFW_KEY_BACKSLASH;
  case AKEYCODE_SEMICOLON: return GLFW_KEY_SEMICOLON;
  case AKEYCODE_APOSTROPHE: return GLFW_KEY_APOSTROPHE;
  case AKEYCODE_SLASH: return GLFW_KEY_SLASH;
  case AKEYCODE_COMMA: return GLFW_KEY_COMMA;
  case AKEYCODE_PERIOD: return GLFW_KEY_PERIOD;
  case AKEYCODE_GRAVE: return GLFW_KEY_GRAVE_ACCENT;
  case AKEYCODE_MENU: return GLFW_KEY_MENU;
  case AKEYCODE_CAPS_LOCK: return GLFW_KEY_CAPS_LOCK;
  case AKEYCODE_SCROLL_LOCK: return GLFW_KEY_SCROLL_LOCK;
  case AKEYCODE_NUM_LOCK: return GLFW_KEY_NUM_LOCK;
  case AKEYCODE_SYSRQ: return GLFW_KEY_PRINT_SCREEN;
  case AKEYCODE_BREAK: return GLFW_KEY_PAUSE;
  case AKEYCODE_INSERT: return GLFW_KEY_INSERT;
  case AKEYCODE_MOVE_HOME: return GLFW_KEY_HOME;
  case AKEYCODE_MOVE_END: return GLFW_KEY_END;
  case AKEYCODE_PAGE_UP: return GLFW_KEY_PAGE_UP;
  case AKEYCODE_PAGE_DOWN: return GLFW_KEY_PAGE_DOWN;
  case AKEYCODE_DPAD_UP: return GLFW_KEY_UP;
  case AKEYCODE_DPAD_DOWN: return GLFW_KEY_DOWN;
  case AKEYCODE_DPAD_LEFT: return GLFW_KEY_LEFT;
  case AKEYCODE_DPAD_RIGHT: return GLFW_KEY_RIGHT;
  case AKEYCODE_NUMPAD_DOT:
  case AKEYCODE_NUMPAD_COMMA: return GLFW_KEY_KP_DECIMAL;
  case AKEYCODE_NUMPAD_ADD: return GLFW_KEY_KP_ADD;
  case AKEYCODE_NUMPAD_SUBTRACT: return GLFW_KEY_KP_SUBTRACT;
  case AKEYCODE_NUMPAD_MULTIPLY: return GLFW_KEY_KP_MULTIPLY;
  case AKEYCODE_NUMPAD_DIVIDE: return GLFW_KEY_KP_DIVIDE;
  case AKEYCODE_NUMPAD_EQUALS: return GLFW_KEY_KP_EQUAL;
  case AKEYCODE_SHIFT_LEFT: return GLFW_KEY_LEFT_SHIFT;
  case AKEYCODE_SHIFT_RIGHT: return GLFW_KEY_RIGHT_SHIFT;
  case AKEYCODE_CTRL_LEFT: return GLFW_KEY_LEFT_CONTROL;
  case AKEYCODE_CTRL_RIGHT: return GLFW_KEY_RIGHT_CONTROL;
  case AKEYCODE_ALT_LEFT: return GLFW_KEY_LEFT_ALT;
  case AKEYCODE_ALT_RIGHT: return GLFW_KEY_RIGHT_ALT;
  case AKEYCODE_META_LEFT: return GLFW_KEY_LEFT_SUPER;
  case AKEYCODE_META_RIGHT: return GLFW_KEY_RIGHT_SUPER;
  default: return GLFW_KEY_UNKNOWN;
  }
}

/// True for anything that can point at the screen: mouse, finger or stylus.
/// Android reports them all as pointer sources, and an on-screen demo wants them
/// folded onto the same left mouse button.
bool isPointerSource(int32_t source) {
  return (source & AINPUT_SOURCE_CLASS_MASK) == AINPUT_SOURCE_CLASS_POINTER;
}

GLFWwindow *dispatchTarget() {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  if (p.currentContext)
    return p.currentContext;
  for (GLFWwindow *candidate : p.windows) {
    if (candidate->ownsSurface)
      return candidate;
  }
  return p.windows.empty() ? nullptr : p.windows.front();
}

void dispatchKey(GLFWwindow *window, int key, int scancode, int action, int mods) {
  if (!window || key == GLFW_KEY_UNKNOWN)
    return;
  if (action == GLFW_PRESS)
    window->keys[key] = GLFW_PRESS;
  else if (action == GLFW_RELEASE)
    window->keys[key] = GLFW_RELEASE;
  if (window->keyCallback)
    window->keyCallback(window, key, scancode, action, mods);
}

void dispatchMouseButton(GLFWwindow *window, int button, int action, int mods) {
  if (!window)
    return;
  window->buttons[button] = static_cast<unsigned char>(action);
  if (window->mouseButtonCallback)
    window->mouseButtonCallback(window, button, action, mods);
}

void dispatchCursorPos(GLFWwindow *window, double x, double y) {
  if (!window)
    return;
  window->cursorX = x;
  window->cursorY = y;
  if (window->cursorPosCallback)
    window->cursorPosCallback(window, x, y);
}

void dispatchCursorEnter(GLFWwindow *window, bool entered) {
  if (!window)
    return;
  window->cursorInside = entered;
  if (window->cursorEnterCallback)
    window->cursorEnterCallback(window, entered ? GLFW_TRUE : GLFW_FALSE);
}

void dispatchScroll(GLFWwindow *window, double x, double y) {
  if (window && window->scrollCallback)
    window->scrollCallback(window, x, y);
}

void dispatchChar(GLFWwindow *window, uint32_t codepoint, int mods) {
  if (!window)
    return;
  if (window->charCallback)
    window->charCallback(window, codepoint);
  if (window->charModsCallback)
    window->charModsCallback(window, codepoint, mods);
}

/// Blocks until the activity hands over a surface, so that the render thread
/// does not race the UI thread into glfwCreateWindow().
ANativeWindow *waitForNativeWindow() {
  Platform &p = platform();
  std::unique_lock<std::recursive_mutex> lock(p.mutex);
  const auto deadline =
      std::chrono::steady_clock::now() + std::chrono::nanoseconds(kSurfaceWaitNs);
  while (!p.nativeWindow) {
    if (p.surfaceCv.wait_until(lock, deadline) == std::cv_status::timeout &&
        !p.nativeWindow)
      return nullptr;
  }
  return acquireWindowLocked();
}

void handleMotion(GLFWwindow *window, const AInputEvent *event) {
  const int32_t source = AInputEvent_getSource(event);
  if (!isPointerSource(source))
    return; // joystick, sensor, ... not supported

  const int32_t action = AMotionEvent_getAction(event) & AMOTION_EVENT_ACTION_MASK;
  switch (action) {
  case AMOTION_EVENT_ACTION_DOWN:
  case AMOTION_EVENT_ACTION_BUTTON_PRESS:
    dispatchCursorPos(window, AMotionEvent_getX(event, 0), AMotionEvent_getY(event, 0));
    if (!window->cursorInside)
      dispatchCursorEnter(window, true);
    dispatchMouseButton(window, GLFW_MOUSE_BUTTON_LEFT, GLFW_PRESS, 0);
    break;
  case AMOTION_EVENT_ACTION_UP:
  case AMOTION_EVENT_ACTION_BUTTON_RELEASE:
    dispatchMouseButton(window, GLFW_MOUSE_BUTTON_LEFT, GLFW_RELEASE, 0);
    break;
  case AMOTION_EVENT_ACTION_CANCEL:
    dispatchMouseButton(window, GLFW_MOUSE_BUTTON_LEFT, GLFW_RELEASE, 0);
    dispatchCursorPos(window, -1.0, -1.0);
    dispatchCursorEnter(window, false);
    break;
  case AMOTION_EVENT_ACTION_MOVE:
  case AMOTION_EVENT_ACTION_HOVER_MOVE:
    // A drag only reports the pointer that moved; index 0 is the primary one,
    // which is as much as a single-pointer UI can use.
    dispatchCursorPos(window, AMotionEvent_getX(event, 0), AMotionEvent_getY(event, 0));
    if (!window->cursorInside)
      dispatchCursorEnter(window, true);
    break;
  case AMOTION_EVENT_ACTION_HOVER_EXIT:
    dispatchCursorEnter(window, false);
    break;
  case AMOTION_EVENT_ACTION_SCROLL:
    // Android's scroll offsets grow the other way round to GLFW's.
    dispatchScroll(window, -AMotionEvent_getXOffset(event),
                   -AMotionEvent_getYOffset(event));
    break;
  default:
    break;
  }
}

/// The looper the input queue is attached to, prepared on -- and therefore
/// pollable by -- whichever thread first asks for input.
///
/// ALooper_pollOnce() always polls the *calling* thread's looper, so the queue
/// cannot be attached to the UI thread's looper and drained from the render
/// thread: there is no API that polls a looper belonging to another thread.
/// The attachment therefore has to happen on the thread that will poll, which is
/// the one V4D's display thread is on. That is where this is called from.
ALooper *inputLooper() {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  if (!p.looper) {
    p.looper = ALooper_forThread();
    if (!p.looper)
      p.looper = ALooper_prepare(ALOOPER_PREPARE_ALLOW_NON_CALLBACKS);
    if (p.looper && p.inputQueue) {
      AInputQueue_attachLooper(p.inputQueue, p.looper, kInputQueueIdent, nullptr,
                               nullptr);
      LOGI("input queue attached to looper %p on this thread", p.looper);
    }
  }
  return p.looper;
}

/// Drains the input queue, firing the GLFW callbacks. This mirrors the NDK's
/// native_app_glue so the input method still sees the events it wants
/// (preDispatch) and every event is released exactly once.
///
/// \param timeoutMs how long to block waiting for input. 0 is the frame loop's
///        "catch up with whatever arrived"; -1 is glfwWaitEvents()'s "block until
///        something happens". ALooper_pollAll() used to do this in one call and
///        is removed from the NDK, so this is the documented replacement: call
///        pollOnce() in a loop, and treat every non-negative return as "wake".
void pumpInput(int timeoutMs) {
  Platform &p = platform();
  AInputQueue *queue = nullptr;
  GlfwAndroidInputHandler handler = nullptr;
  {
    std::lock_guard<std::recursive_mutex> lock(p.mutex);
    queue = p.inputQueue;
    handler = p.inputHandler;
  }
  if (!queue || !inputLooper())
    return;

  int fd = 0, events = 0;
  void *data = nullptr;
  while (true) {
    const int result = ALooper_pollOnce(timeoutMs, &fd, &events, &data);
    timeoutMs = 0; // only the first call may wait
    if (result < 0)
      return; // this thread has no looper, or the looper is gone
    // Any wakeup counts, not only the ones that carry our identifier -- that is
    // the one thing ALooper_pollAll() did for us and pollOnce() does not.
    if (result != kInputQueueIdent)
      return;

    AInputEvent *event = nullptr;
    while (AInputQueue_getEvent(queue, &event) >= 0) {
      if (AInputQueue_preDispatchEvent(queue, event))
        continue; // the input method consumed it; it finishes itself

      int32_t handled = 0;
      if (handler)
        handled = handler(event);

      GLFWwindow *window = dispatchTarget();
      switch (AInputEvent_getType(event)) {
      case AINPUT_EVENT_TYPE_KEY: {
        const int32_t keycode = AKeyEvent_getKeyCode(event);
        const int32_t source = AInputEvent_getSource(event);
        const int key = glfwKeyFromAndroid(keycode, source);
        const int32_t action = AKeyEvent_getAction(event);
        int glfwAction = GLFW_RELEASE;
        if (action == AKEY_EVENT_ACTION_DOWN) {
          // Auto-repeat arrives as a repeat count on the "down" action, which is
          // GLFW_REPEAT rather than a second press.
          glfwAction =
              AKeyEvent_getRepeatCount(event) > 0 ? GLFW_REPEAT : GLFW_PRESS;
        }
        dispatchKey(window, key, static_cast<int>(AKeyEvent_getScanCode(event)),
                    glfwAction, glfwModsFromMetaState(AKeyEvent_getMetaState(event)));
        // There is no separate "text" event any more: an input method delivers
        // characters as key events with AKEY_EVENT_FLAG_SOFT_KEYBOARD set. The
        // NDK exposes no Unicode accessor for them, so the codepoint comes from
        // ImGui's backend (which is handed the raw events) and from whatever an
        // app derives itself -- see glfw_android.hpp's input handler hook.
        break;
      }
      case AINPUT_EVENT_TYPE_MOTION:
        handleMotion(window, event);
        break;
      default:
        break;
      }
      AInputQueue_finishEvent(queue, event, handled);
    }
  }
}

/// (Re)creates the EGL surface for whatever native window is current. The surface
/// belongs to one ANativeWindow, so coming back from the background -- where the
/// old one was destroyed -- needs a new one.
///
/// Only the window that owns the activity's surface has one; the offscreen
/// children have pbuffers that nothing destroys behind their back.
void refreshSurface(GLFWwindow *window) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  if (!window || !window->ownsSurface || !p.resumed || !p.nativeWindow)
    return;
  if (window->nativeWindow == p.nativeWindow && window->surface)
    return;

  if (window->surface) {
    eglMakeCurrent(window->display, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
    eglDestroySurface(window->display, window->surface);
    window->surface = nullptr;
  }
  if (window->nativeWindow)
    ANativeWindow_release(window->nativeWindow);
  window->nativeWindow = acquireWindowLocked();

  window->surface = eglCreateWindowSurface(window->display, window->config,
                                           window->nativeWindow, nullptr);
  if (window->surface == EGL_NO_SURFACE) {
    reportError(GLFW_PLATFORM_ERROR, "eglCreateWindowSurface failed (0x%x)",
                eglGetError());
    window->surface = nullptr;
    return;
  }
  eglMakeCurrent(window->display, window->surface, window->surface, window->context);
  eglSwapInterval(window->display, window->swapInterval);
  LOGI("surface is now %dx%d", window->width, window->height);
}

/// One attribute of a config, or -1 when the driver will not say. Only used for
/// the log line: a config is chosen by what was asked for, not by reading it back.
EGLint configAttrib(EGLDisplay display, EGLConfig config, EGLint attribute) {
  EGLint value = -1;
  eglGetConfigAttrib(display, config, attribute, &value);
  return value;
}

/// Picks one EGL config, relaxing the request until the driver has something.
///
/// A single config has to serve two kinds of window: the one that owns the
/// activity's surface needs EGL_WINDOW_BIT, the offscreen children need
/// EGL_PBUFFER_BIT, and eglCreatePbufferSurface rejects a config that lacks the
/// latter with EGL_BAD_MATCH. Asking for both bits in one go is what makes that
/// work, and if a driver has no such config the caller is better served by a
/// plainer one than by no config at all.
EGLConfig chooseConfig(EGLDisplay display, const WindowHints &hints) {
  const bool wantsSamples = hints.samples > 0;
  // Dropped one at a time: the extras first, since they are the ones a driver is
  // most likely to refuse, and the colour and buffer sizes last.
  for (int relax = 0; relax < 5; ++relax) {
    std::vector<EGLint> attribs = {EGL_RENDERABLE_TYPE, EGL_OPENGL_ES3_BIT,
                                   EGL_SURFACE_TYPE, EGL_WINDOW_BIT | EGL_PBUFFER_BIT};
    if (relax < 4) {
      attribs.insert(attribs.end(), {EGL_RED_SIZE, hints.red, EGL_GREEN_SIZE,
                                     hints.green, EGL_BLUE_SIZE, hints.blue});
    }
    if (relax < 3)
      attribs.insert(attribs.end(), {EGL_ALPHA_SIZE, hints.alpha});
    if (relax < 2)
      attribs.insert(attribs.end(), {EGL_DEPTH_SIZE, hints.depth});
    if (relax < 1)
      attribs.insert(attribs.end(), {EGL_STENCIL_SIZE, hints.stencil});
    if (wantsSamples)
      attribs.insert(attribs.end(), {EGL_SAMPLES, hints.samples});
    attribs.push_back(EGL_NONE);

    EGLint count = 0;
    if (!eglChooseConfig(display, attribs.data(), nullptr, 0, &count) || count == 0)
      continue;
    std::vector<EGLConfig> configs(static_cast<size_t>(count));
    eglChooseConfig(display, attribs.data(), configs.data(), count, &count);

    // Multisampling is asked for through GLFW_SAMPLES exactly as on the desktop;
    // the config with the fewest samples that satisfies the request keeps the
    // swap chain within what the driver will allocate.
    for (EGLint i = 0; i < count; ++i) {
      EGLint got = 0;
      eglGetConfigAttrib(display, configs[static_cast<size_t>(i)], EGL_SAMPLES, &got);
      if (!wantsSamples || got <= hints.samples) {
        LOGI("EGL config %d of %d: samples=%d rgba=%d/%d/%d/%d depth=%d stencil=%d",
             i, count, got, configAttrib(display, configs[static_cast<size_t>(i)],
                                         EGL_RED_SIZE),
             configAttrib(display, configs[static_cast<size_t>(i)], EGL_GREEN_SIZE),
             configAttrib(display, configs[static_cast<size_t>(i)], EGL_BLUE_SIZE),
             configAttrib(display, configs[static_cast<size_t>(i)], EGL_ALPHA_SIZE),
             configAttrib(display, configs[static_cast<size_t>(i)], EGL_DEPTH_SIZE),
             configAttrib(display, configs[static_cast<size_t>(i)], EGL_STENCIL_SIZE));
        return configs[static_cast<size_t>(i)];
      }
    }
    return configs.front();
  }
  reportError(GLFW_PLATFORM_ERROR,
              "no EGL config with an ES3 window surface");
  return nullptr;
}

/// The process-wide EGL display, initialised on first use. Every window takes a
/// reference, released when it is destroyed; the display is terminated when the
/// last one goes.
EGLDisplay acquireDisplay() {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  if (p.display == EGL_NO_DISPLAY) {
    EGLDisplay display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
    if (display == EGL_NO_DISPLAY ||
        !eglInitialize(display, &p.eglMajor, &p.eglMinor)) {
      reportError(GLFW_PLATFORM_ERROR, "eglInitialize failed (0x%x)", eglGetError());
      return EGL_NO_DISPLAY;
    }
    p.display = display;
    p.config = nullptr;
    p.configValid = false;
    LOGI("EGL %d.%d", p.eglMajor, p.eglMinor);
  }
  ++p.displayUsers;
  return p.display;
}

void releaseDisplay(EGLDisplay display) {
  if (display == EGL_NO_DISPLAY)
    return;
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  if (p.displayUsers > 0 && --p.displayUsers > 0)
    return;
  p.displayUsers = 0;
  p.config = nullptr;
  p.configValid = false;
  p.display = EGL_NO_DISPLAY;
  eglTerminate(display);
}

/// The config for these hints, picked once per display. It only depends on the
/// display and on the attributes below, and every V4D window asks for the same
/// ones, so in practice this is one eglChooseConfig for the whole process.
EGLConfig acquireConfig(EGLDisplay display, const WindowHints &hints) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  const bool sameHints =
      p.configValid && p.configHints.samples == hints.samples &&
      p.configHints.red == hints.red && p.configHints.green == hints.green &&
      p.configHints.blue == hints.blue && p.configHints.alpha == hints.alpha &&
      p.configHints.depth == hints.depth && p.configHints.stencil == hints.stencil;
  if (sameHints && p.config)
    return p.config;
  EGLConfig config = chooseConfig(display, hints);
  p.config = config;
  p.configValid = config != nullptr;
  p.configHints = hints;
  return config;
}

void destroyWindowResources(GLFWwindow *window) {
  if (!window)
    return;
  if (window->display != EGL_NO_DISPLAY) {
    if (window->surface != EGL_NO_SURFACE)
      eglDestroySurface(window->display, window->surface);
    if (window->context != EGL_NO_CONTEXT)
      eglDestroyContext(window->display, window->context);
  }
  window->surface = nullptr;
  window->context = nullptr;
  if (window->nativeWindow)
    ANativeWindow_release(window->nativeWindow);
  window->nativeWindow = nullptr;
  releaseDisplay(window->display);
  window->display = EGL_NO_DISPLAY;
}

} // namespace

// ---------------------------------------------------------------------------
// Activity plumbing (called from android_main.cpp)
// ---------------------------------------------------------------------------

void glfw_android_set_activity(ANativeActivity *activity) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  p.activity = activity;
  if (activity)
    LOGI("activity %s", activity->internalDataPath ? activity->internalDataPath
                                                   : "(no data path)");
}

void glfw_android_set_input_queue(AInputQueue *queue) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  // This is called from the UI thread, which is not the thread that polls, so the
  // attach is deferred to inputLooper() on the first poll. The queue can be
  // attached to a looper owned by another thread as long as that thread polls
  // it; what it cannot do is be polled from here.
  p.inputQueue = queue;
  if (!queue) {
    p.looper = nullptr;
    return;
  }
  if (p.looper)
    AInputQueue_attachLooper(queue, p.looper, kInputQueueIdent, nullptr, nullptr);
}

void glfw_android_set_native_window(ANativeWindow *window) {
  Platform &p = platform();
  {
    std::lock_guard<std::recursive_mutex> lock(p.mutex);
    p.nativeWindow = window;
    if (window)
      ++p.windowGeneration;
  }
  p.surfaceCv.notify_all();
}

void glfw_android_clear_native_window(ANativeWindow *window) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  if (p.nativeWindow == window) {
    p.nativeWindow = nullptr;
    ++p.windowGeneration;
    p.surfaceCv.notify_all();
  }
}

void glfw_android_set_activity_resumed(bool resumed) {
  Platform &p = platform();
  {
    std::lock_guard<std::recursive_mutex> lock(p.mutex);
    p.resumed = resumed;
    if (resumed)
      p.surfaceCv.notify_all();
  }
}

void glfw_android_set_display_size(int widthPx, int heightPx) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  p.displayWidthPx = widthPx;
  p.displayHeightPx = heightPx;
}

ANativeWindow *glfw_android_acquire_native_window() {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  return acquireWindowLocked();
}

uint64_t glfw_android_native_window_generation() {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  return p.windowGeneration;
}

GlfwAndroidInputHandler glfw_android_set_input_handler(GlfwAndroidInputHandler handler) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  GlfwAndroidInputHandler previous = p.inputHandler;
  p.inputHandler = handler;
  return previous;
}

// ---------------------------------------------------------------------------
// The GLFW API
// ---------------------------------------------------------------------------

extern "C" {

int glfwInit(void) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  if (p.initialized)
    return GLFW_TRUE;
  p.initialized = true;
  p.hints = WindowHints{};
  p.primaryMonitor.mode = GLFWvidmode{0, 0, 8, 8, 8, 60};
  LOGI("glfwInit: GLFW replaced by the Android shim");
  return GLFW_TRUE;
}

void glfwTerminate(void) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  for (GLFWwindow *window : p.windows)
    destroyWindowResources(window);
  p.windows.clear();
  p.currentContext = nullptr;
  p.initialized = false;
}

void glfwInitHint(int hint, int value) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  if (hint == GLFW_PLATFORM) {
    // There is exactly one platform here; asking for another is a mistake worth
    // reporting, because on the desktop this hint selects X11 vs Wayland.
    if (value != GLFW_PLATFORM_ANDROID)
      reportError(GLFW_INVALID_VALUE,
                  "GLFW_PLATFORM must be GLFW_PLATFORM_ANDROID");
    return;
  }
  LOGW("glfwInitHint(0x%x, 0x%x) ignored", hint, value);
}

void glfwGetVersion(int *major, int *minor, int *rev) {
  if (major)
    *major = GLFW_VERSION_MAJOR;
  if (minor)
    *minor = GLFW_VERSION_MINOR;
  if (rev)
    *rev = GLFW_VERSION_REVISION;
}

int glfwGetError(const char **description) {
  Platform &p = platform();
  if (description)
    *description = p.lastErrorText.c_str();
  const int code = p.lastError;
  p.lastError = GLFW_NO_ERROR;
  p.lastErrorText.clear();
  return code;
}

GLFWerrorfun glfwSetErrorCallback(GLFWerrorfun callback) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  GLFWerrorfun previous = p.errorCallback;
  p.errorCallback = callback;
  return previous;
}

int glfwGetPlatform(void) { return GLFW_PLATFORM_ANDROID; }

int glfwPlatformSupported(int platform) {
  // framebuffercontext.cpp asks about Wayland behind a version check; the answer
  // has to be false here, because there is no X11 or Wayland display to connect
  // to and taking the branch would fail at the next window creation.
  return platform == GLFW_PLATFORM_ANDROID ? GLFW_TRUE : GLFW_FALSE;
}

GLFWmonitor *glfwGetPrimaryMonitor(void) { return &platform().primaryMonitor; }

void glfwGetMonitors(GLFWmonitor **monitors, int *count) {
  if (monitors && count) {
    monitors[0] = &platform().primaryMonitor;
    *count = 1;
  }
}

void glfwGetMonitorPos(GLFWmonitor *, int *xpos, int *ypos) {
  if (xpos)
    *xpos = 0;
  if (ypos)
    *ypos = 0;
}

void glfwGetMonitorWorkarea(GLFWmonitor *, int *xpos, int *ypos, int *width,
                            int *height) {
  Platform &p = platform();
  if (xpos)
    *xpos = 0;
  if (ypos)
    *ypos = 0;
  if (width)
    *width = p.primaryMonitor.mode.width;
  if (height)
    *height = p.primaryMonitor.mode.height;
}

void glfwGetMonitorPhysicalSize(GLFWmonitor *monitor, int *widthMM, int *heightMM) {
  if (widthMM)
    *widthMM = monitor ? monitor->widthMM : 0;
  if (heightMM)
    *heightMM = monitor ? monitor->heightMM : 0;
}

void glfwGetMonitorContentScale(GLFWmonitor *, float *xscale, float *yscale) {
  // Android already works in pixels; the context scale is always 1.
  if (xscale)
    *xscale = 1.f;
  if (yscale)
    *yscale = 1.f;
}

void glfwSetMonitorUserPointer(GLFWmonitor *monitor, void *pointer) {
  if (monitor)
    monitor->userPointer = pointer;
}

void *glfwGetMonitorUserPointer(GLFWmonitor *monitor) {
  return monitor ? monitor->userPointer : nullptr;
}

void glfwSetMonitorCallback(GLFWmonitorfun callback) {
  platform().monitorCallback = callback;
}

const GLFWvidmode *glfwGetVideoModes(GLFWmonitor *, int *count) {
  refreshDisplayMode();
  if (count)
    *count = 1;
  return &platform().primaryMonitor.mode;
}

const GLFWvidmode *glfwGetVideoMode(GLFWmonitor *) {
  refreshDisplayMode();
  return &platform().primaryMonitor.mode;
}

GLFWwindow *glfwCreateWindow(int width, int height, const char *, GLFWmonitor *monitor,
                             GLFWwindow *share) {
  Platform &p = platform();
  if (!p.initialized && glfwInit() != GLFW_TRUE)
    return nullptr;

  // Android hands an app exactly one window, and the activity owns its surface,
  // so only the first window can have a window surface. Every later one is a
  // child context V4D renders offscreen into -- NanoVG's, a GL context's, a
  // second plan's -- and gets an offscreen surface instead.
  //
  // This is not a workaround: an ANativeWindow can be connected to a graphics
  // API exactly once, so a second eglCreateWindowSurface() on it fails with
  // EGL_BAD_ALLOC and libEGL's real complaint,
  // "native_window_api_connect ... failed (already connected to another API?)".
  WindowHints hints;
  bool ownsSurface;
  {
    std::lock_guard<std::recursive_mutex> lock(p.mutex);
    ownsSurface = p.windows.empty();
    hints = p.hints;
  }

  ANativeWindow *nativeWindow = nullptr;
  if (ownsSurface) {
    nativeWindow = waitForNativeWindow();
    if (!nativeWindow) {
      reportError(GLFW_PLATFORM_ERROR,
                  "no surface from the activity after 10s; cannot create a window");
      return nullptr;
    }
  }

  EGLDisplay display = acquireDisplay();
  if (display == EGL_NO_DISPLAY) {
    if (nativeWindow)
      ANativeWindow_release(nativeWindow);
    return nullptr;
  }
  // OpenGL ES is the only client API Android has; binding anything else would
  // fail later with a much less obvious message.
  if (!eglBindAPI(EGL_OPENGL_ES_API)) {
    reportError(GLFW_API_UNAVAILABLE, "eglBindAPI(EGL_OPENGL_ES_API) failed");
    releaseDisplay(display);
    if (nativeWindow)
      ANativeWindow_release(nativeWindow);
    return nullptr;
  }

  EGLConfig config = acquireConfig(display, hints);
  if (!config) {
    releaseDisplay(display);
    if (nativeWindow)
      ANativeWindow_release(nativeWindow);
    return nullptr;
  }

  auto *window = new GLFWwindow();
  window->width = width > 0 ? width : (nativeWindow ? ANativeWindow_getWidth(nativeWindow) : 1);
  window->height =
      height > 0 ? height : (nativeWindow ? ANativeWindow_getHeight(nativeWindow) : 1);
  window->monitor = monitor;
  window->share = share;
  window->visible = hints.visible;
  window->resizable = hints.resizable;
  window->decorated = hints.decorated;
  window->focused = hints.focused;
  window->contextVersionMajor = hints.contextVersionMajor;
  window->contextVersionMinor = hints.contextVersionMinor;
  window->nativeWindow = nativeWindow; // the reference from waitForNativeWindow()
  window->ownsSurface = ownsSurface;
  window->display = display;
  window->config = config;

  const EGLint contextAttribs[] = {EGL_CONTEXT_CLIENT_VERSION,
                                   window->contextVersionMajor, EGL_NONE};
  window->context = eglCreateContext(
      display, config, share ? share->context : EGL_NO_CONTEXT, contextAttribs);
  if (window->context == EGL_NO_CONTEXT) {
    reportError(GLFW_API_UNAVAILABLE, "eglCreateContext failed (0x%x)", eglGetError());
    destroyWindowResources(window);
    delete window;
    return nullptr;
  }

  if (ownsSurface) {
    window->surface =
        eglCreateWindowSurface(display, config, window->nativeWindow, nullptr);
    if (window->surface == EGL_NO_SURFACE) {
      reportError(GLFW_PLATFORM_ERROR, "eglCreateWindowSurface failed (0x%x)",
                  eglGetError());
      destroyWindowResources(window);
      delete window;
      return nullptr;
    }
  } else {
    const EGLint pbufferAttribs[] = {EGL_WIDTH, window->width, EGL_HEIGHT,
                                     window->height, EGL_NONE};
    window->surface = eglCreatePbufferSurface(display, config, pbufferAttribs);
    if (window->surface == EGL_NO_SURFACE) {
      reportError(GLFW_PLATFORM_ERROR, "eglCreatePbufferSurface failed (0x%x)",
                  eglGetError());
      destroyWindowResources(window);
      delete window;
      return nullptr;
    }
  }

  // V4D creates the window from its display thread and renders there, so the
  // context is made current on this thread straight away rather than waiting for
  // an explicit glfwMakeContextCurrent().
  eglMakeCurrent(display, window->surface, window->surface, window->context);
  eglSwapInterval(display, 0);

  {
    std::lock_guard<std::recursive_mutex> lock(p.mutex);
    p.currentContext = window;
    p.windows.push_back(window);
  }
  LOGI("glfwCreateWindow: %dx%d (requested %dx%d, EGL %d.%d)%s", window->width,
       window->height, width, height, p.eglMajor, p.eglMinor,
       ownsSurface ? "" : " [offscreen]");
  return window;
}

void glfwDestroyWindow(GLFWwindow *window) {
  if (!window)
    return;
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  auto it = std::find(p.windows.begin(), p.windows.end(), window);
  if (it != p.windows.end())
    p.windows.erase(it);
  if (p.currentContext == window)
    p.currentContext = p.windows.empty() ? nullptr : p.windows.front();
  destroyWindowResources(window);
  delete window;
}

// Android owns the surface: a window is visible for as long as the activity is
// resumed, and there is no title bar or icon to act on. These keep the V4D API
// honest instead of pretending a window system is there.
void glfwShowWindow(GLFWwindow *window) {
  if (window)
    window->visible = true;
}

void glfwHideWindow(GLFWwindow *window) {
  if (window)
    window->visible = false;
}

void glfwIconifyWindow(GLFWwindow *window) {
  if (window)
    window->iconified = true;
}

void glfwRestoreWindow(GLFWwindow *window) {
  if (window)
    window->iconified = false;
}

void glfwMaximizeWindow(GLFWwindow *) {}

int glfwWindowShouldClose(GLFWwindow *window) {
  return !window || window->shouldClose ? GLFW_TRUE : GLFW_FALSE;
}

void glfwSetWindowShouldClose(GLFWwindow *window, int value) {
  if (!window)
    return;
  window->shouldClose = value != GLFW_FALSE;
  // There is no close button to click, so honour the request by running the
  // callback here, exactly once.
  if (window->shouldClose && window->closeCallback)
    window->closeCallback(window);
}

void glfwSetWindowUserPointer(GLFWwindow *window, void *pointer) {
  if (window)
    window->userPointer = pointer;
}

void *glfwGetWindowUserPointer(GLFWwindow *window) {
  return window ? window->userPointer : nullptr;
}

void glfwSetWindowTitle(GLFWwindow *, const char *) {}

void glfwSetWindowPos(GLFWwindow *window, int xpos, int ypos) {
  if (!window)
    return;
  window->xpos = xpos;
  window->ypos = ypos;
  if (window->posCallback)
    window->posCallback(window, xpos, ypos);
}

void glfwGetWindowPos(GLFWwindow *window, int *xpos, int *ypos) {
  if (xpos)
    *xpos = window ? window->xpos : 0;
  if (ypos)
    *ypos = window ? window->ypos : 0;
}

void glfwSetWindowSize(GLFWwindow *window, int width, int height) {
  // The activity decides the surface size, so a request is only remembered -- and
  // only for an offscreen window, whose "surface" is a pbuffer it could resize.
  // For the window that owns the activity's surface the request is inert:
  // drawableSize() reports what Android actually gave us.
  if (!window || window->ownsSurface)
    return;
  window->width = width;
  window->height = height;
}

void glfwGetWindowSize(GLFWwindow *window, int *width, int *height) {
  int w = 0, h = 0;
  drawableSize(window, w, h);
  if (width)
    *width = w;
  if (height)
    *height = h;
}

void glfwGetFramebufferSize(GLFWwindow *window, int *width, int *height) {
  glfwGetWindowSize(window, width, height);
}

void glfwGetWindowContentScale(GLFWwindow *window, float *xscale, float *yscale) {
  if (xscale)
    *xscale = window ? window->xscale : 1.f;
  if (yscale)
    *yscale = window ? window->yscale : 1.f;
}

void glfwGetWindowFrameSize(GLFWwindow *, int *left, int *top, int *right,
                            int *bottom) {
  // No decorations, so no borders.
  if (left)
    *left = 0;
  if (top)
    *top = 0;
  if (right)
    *right = 0;
  if (bottom)
    *bottom = 0;
}

void glfwSetWindowSizeLimits(GLFWwindow *, int, int, int, int) {}

void glfwSetWindowAspectRatio(GLFWwindow *, float, float) {}

void glfwGetWindowAspectRatio(GLFWwindow *, float *numer, float *denom) {
  if (numer)
    *numer = 16.f;
  if (denom)
    *denom = 9.f;
}

void glfwSetWindowMonitor(GLFWwindow *window, GLFWmonitor *monitor, int, int, int, int,
                          int) {
  // Fullscreen is the activity's business, not the window's.
  if (window)
    window->monitor = monitor;
}

GLFWmonitor *glfwGetWindowMonitor(GLFWwindow *window) {
  return window ? window->monitor : nullptr;
}

void glfwSetWindowIcon(GLFWwindow *, int, const GLFWimage *) {}

void glfwSetWindowAttrib(GLFWwindow *window, int attrib, int value) {
  if (!window)
    return;
  switch (attrib) {
  case GLFW_RESIZABLE:
  case GLFW_AUTO_ICONIFY: window->resizable = value != GLFW_FALSE; break;
  case GLFW_DECORATED:
  case GLFW_FLOATING: window->decorated = value != GLFW_FALSE; break;
  case GLFW_FOCUSED: window->focused = value != GLFW_FALSE; break;
  case GLFW_VISIBLE: window->visible = value != GLFW_FALSE; break;
  default: reportError(GLFW_INVALID_ENUM, "glfwSetWindowAttrib: 0x%x", attrib); break;
  }
}

int glfwGetWindowAttrib(GLFWwindow *window, int attrib) {
  if (!window)
    return 0;
  switch (attrib) {
  case GLFW_CONTEXT_VERSION_MAJOR: return window->contextVersionMajor;
  case GLFW_CONTEXT_VERSION_MINOR: return window->contextVersionMinor;
  case GLFW_CLIENT_API: return GLFW_OPENGL_ES_API;
  case GLFW_CONTEXT_CREATION_API: return GLFW_EGL_CONTEXT_API;
  case GLFW_RESIZABLE: return window->resizable ? GLFW_TRUE : GLFW_FALSE;
  case GLFW_DECORATED: return window->decorated ? GLFW_TRUE : GLFW_FALSE;
  case GLFW_FLOATING: return window->floating ? GLFW_TRUE : GLFW_FALSE;
  case GLFW_FOCUSED: return window->focused ? GLFW_TRUE : GLFW_FALSE;
  case GLFW_VISIBLE: return window->visible ? GLFW_TRUE : GLFW_FALSE;
  case GLFW_ICONIFIED: return window->iconified ? GLFW_TRUE : GLFW_FALSE;
  // The activity fills the screen.
  case GLFW_MAXIMIZED: return GLFW_TRUE;
  default: return 0;
  }
}

void glfwSetWindowPosCallback(GLFWwindow *w, GLFWwindowposfun cb) {
  if (w)
    w->posCallback = cb;
}
void glfwSetWindowSizeCallback(GLFWwindow *w, GLFWwindowsizefun cb) {
  if (w)
    w->sizeCallback = cb;
}
void glfwSetWindowCloseCallback(GLFWwindow *w, GLFWwindowclosefun cb) {
  if (w)
    w->closeCallback = cb;
}
void glfwSetWindowRefreshCallback(GLFWwindow *w, GLFWwindowrefreshfun cb) {
  if (w)
    w->refreshCallback = cb;
}
void glfwSetWindowFocusCallback(GLFWwindow *w, GLFWwindowfocusfun cb) {
  if (w)
    w->focusCallback = cb;
}
void glfwSetWindowIconifyCallback(GLFWwindow *w, GLFWwindowiconifyfun cb) {
  if (w)
    w->iconifyCallback = cb;
}
void glfwSetWindowMaximizeCallback(GLFWwindow *w, GLFWwindowmaximizefun cb) {
  if (w)
    w->maximizeCallback = cb;
}
void glfwSetFramebufferSizeCallback(GLFWwindow *w, GLFWframebuffersizefun cb) {
  if (w)
    w->framebufferSizeCallback = cb;
}
void glfwSetWindowContentScaleCallback(GLFWwindow *w, GLFWwindowcontentscalefun cb) {
  if (w)
    w->contentScaleCallback = cb;
}
void glfwSetMouseButtonCallback(GLFWwindow *w, GLFWmousebuttonfun cb) {
  if (w)
    w->mouseButtonCallback = cb;
}
void glfwSetCursorPosCallback(GLFWwindow *w, GLFWcursorposfun cb) {
  if (w)
    w->cursorPosCallback = cb;
}
void glfwSetCursorEnterCallback(GLFWwindow *w, GLFWcursorenterfun cb) {
  if (w)
    w->cursorEnterCallback = cb;
}
void glfwSetScrollCallback(GLFWwindow *w, GLFWscrollfun cb) {
  if (w)
    w->scrollCallback = cb;
}
void glfwSetKeyCallback(GLFWwindow *w, GLFWkeyfun cb) {
  if (w)
    w->keyCallback = cb;
}
void glfwSetCharCallback(GLFWwindow *w, GLFWcharfun cb) {
  if (w)
    w->charCallback = cb;
}
void glfwSetCharModsCallback(GLFWwindow *w, GLFWcharmodsfun cb) {
  if (w)
    w->charModsCallback = cb;
}

int glfwGetKey(GLFWwindow *window, int key) {
  if (!window || key < 0 || key > GLFW_KEY_LAST)
    return GLFW_RELEASE;
  return window->keys[key];
}

int glfwGetMouseButton(GLFWwindow *window, int button) {
  if (!window || button < 0 || button > GLFW_MOUSE_BUTTON_LAST)
    return GLFW_RELEASE;
  return window->buttons[button];
}

void glfwGetCursorPos(GLFWwindow *window, double *xpos, double *ypos) {
  if (xpos)
    *xpos = window ? window->cursorX : 0.0;
  if (ypos)
    *ypos = window ? window->cursorY : 0.0;
}

void glfwSetCursorPos(GLFWwindow *, double, double) {}

int glfwGetInputMode(GLFWwindow *, int) { return GLFW_CURSOR_NORMAL; }

void glfwSetInputMode(GLFWwindow *, int, int) {}

int glfwRawMouseMotionSupported(void) { return GLFW_FALSE; }

void glfwGetRawMouseMotion(double *xpos, double *ypos) {
  if (xpos)
    *xpos = 0.0;
  if (ypos)
    *ypos = 0.0;
}

// GLFW scancodes are platform specific and GLFW defines no constants for them,
// so the Linux keycode AKeyEvent_getScanCode() reports is the most useful thing
// to hand on -- it is what GLFW itself passes on X11.
const char *glfwGetKeyName(int, int) { return nullptr; }

char **glfwGetClipboardString(GLFWwindow *) { return nullptr; }
void glfwSetClipboardString(GLFWwindow *, const char *) {}
void glfwFreeUserPointer(void *) {}

// Joysticks need the AMotionEvent controller APIs and their own permission
// story. Reporting none present keeps gwe's polling loop a quiet no-op instead
// of inventing input no device is producing.
int glfwJoystickPresent(int) { return GLFW_FALSE; }
int glfwJoystickIsGamepad(int) { return GLFW_FALSE; }
const float *glfwGetJoystickAxes(int, int *count) {
  if (count)
    *count = 0;
  return nullptr;
}
const unsigned char *glfwGetJoystickButtons(int, int *count) {
  if (count)
    *count = 0;
  return nullptr;
}
const unsigned char *glfwGetJoystickHats(int, int *count) {
  if (count)
    *count = 0;
  return nullptr;
}
const char *glfwGetJoystickName(int) { return nullptr; }
const char *glfwGetGamepadName(int) { return nullptr; }
int glfwGetGamepadState(int, GLFWgamepadstate *state) {
  if (state)
    memset(state, 0, sizeof(*state));
  return GLFW_FALSE;
}
void glfwUpdateGamepadMappings(void) {}

void glfwSetJoystickCallback(GLFWjoystickfun callback) {
  platform().joystickCallback = callback;
}

void glfwPollEvents(void) {
  Platform &p = platform();
  {
    std::lock_guard<std::recursive_mutex> lock(p.mutex);
    // Nothing to poll without an activity, and nothing worth polling while
    // backgrounded.
    if (!p.inputQueue)
      return;
  }
  pumpInput(0);
  if (p.currentContext)
    updateSizeAndNotify(p.currentContext);
}

void glfwWaitEvents(void) {
  Platform &p = platform();
  {
    std::lock_guard<std::recursive_mutex> lock(p.mutex);
    if (!p.inputQueue)
      return;
  }
  // The lock must not be held here: this blocks until an event arrives, and the
  // activity callbacks need it to publish one.
  pumpInput(-1);
  if (p.currentContext)
    updateSizeAndNotify(p.currentContext);
}

void glfwWaitEventsTimeout(double timeout) {
  Platform &p = platform();
  {
    std::lock_guard<std::recursive_mutex> lock(p.mutex);
    if (!p.inputQueue)
      return;
  }
  const int32_t millis = timeout <= 0.0 ? 0 : static_cast<int32_t>(timeout * 1000.0);
  pumpInput(millis);
  if (p.currentContext)
    updateSizeAndNotify(p.currentContext);
}

void glfwPostEmptyEvent(void) {}

void glfwWindowHint(int hint, int value) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  switch (hint) {
  case GLFW_CONTEXT_VERSION_MAJOR: p.hints.contextVersionMajor = value; break;
  case GLFW_CONTEXT_VERSION_MINOR: p.hints.contextVersionMinor = value; break;
  case GLFW_CLIENT_API:
    // ES is the only client API here; note the request and carry on rather than
    // failing a sample that asks for the desktop default.
    if (value != GLFW_OPENGL_ES_API)
      LOGW("GLFW_CLIENT_API is OpenGL ES on Android; ignoring the request");
    break;
  case GLFW_CONTEXT_CREATION_API:
    if (value != GLFW_EGL_CONTEXT_API)
      LOGW("only the EGL context creation API exists on Android");
    break;
  case GLFW_SAMPLES: p.hints.samples = value; break;
  case GLFW_RESIZABLE: p.hints.resizable = value != GLFW_FALSE; break;
  case GLFW_VISIBLE: p.hints.visible = value != GLFW_FALSE; break;
  case GLFW_DECORATED: p.hints.decorated = value != GLFW_FALSE; break;
  case GLFW_FOCUSED: p.hints.focused = value != GLFW_FALSE; break;
  // Colours, profile, focus-on-show and the rest have no Android meaning.
  default: break;
  }
}

void glfwDefaultWindowHints(void) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  p.hints = WindowHints{};
}

void glfwMakeContextCurrent(GLFWwindow *window) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  if (!window || !window->display) {
    eglMakeCurrent(EGL_NO_DISPLAY, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
    p.currentContext = nullptr;
    return;
  }
  eglMakeCurrent(window->display, window->surface, window->surface, window->context);
  p.currentContext = window;
}

GLFWwindow *glfwGetCurrentContext(void) { return platform().currentContext; }

void glfwSwapBuffers(GLFWwindow *window) {
  if (!window)
    return;
  Platform &p = platform();
  {
    std::lock_guard<std::recursive_mutex> lock(p.mutex);
    // Backgrounded: there is no surface to present to, and calling into EGL with
    // the stale one would fail on every single frame.
    if (!p.resumed)
      return;
  }
  if (!window->ownsSurface) {
    // An offscreen window has nothing to present. Swapping a pbuffer is either a
    // no-op or EGL_BAD_SURFACE depending on the driver, and either way V4D only
    // ever renders into these and reads them back, so it is skipped outright.
    return;
  }
  refreshSurface(window);
  if (!window->surface)
    return;
  updateSizeAndNotify(window);
  if (eglSwapBuffers(window->display, window->surface) != GLFW_TRUE)
    LOGW("eglSwapBuffers failed (0x%x); the surface will be rebuilt", eglGetError());
}

void glfwSwapInterval(int interval) {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  if (!p.currentContext || p.currentContext->display == EGL_NO_DISPLAY)
    return;
  p.currentContext->swapInterval = interval;
  eglSwapInterval(p.currentContext->display, interval);
}

GLFWglproc glfwGetProcAddress(const char *procname) {
  if (!procname)
    return nullptr;
  return reinterpret_cast<GLFWglproc>(eglGetProcAddress(procname));
}

double glfwGetTime(void) {
  Platform &p = platform();
  return monotonicSeconds() - p.timeOffset;
}

void glfwSetTime(double time) { platform().timeOffset = monotonicSeconds() - time; }

void glfwGetTimeValue(double *time) {
  if (time)
    *time = glfwGetTime();
}

// There is no desktop to ask about, but FrameBufferContext wants a size before
// the first frame, so report whatever the surface says once it exists.
void refreshDisplayMode() {
  Platform &p = platform();
  std::lock_guard<std::recursive_mutex> lock(p.mutex);
  int width = 0, height = 0;
  if (p.nativeWindow) {
    width = ANativeWindow_getWidth(p.nativeWindow);
    height = ANativeWindow_getHeight(p.nativeWindow);
  }
  if (width <= 0 || height <= 0) {
    // No surface yet. ANativeActivity has no configuration field, so fall back
    // to the display size the platform already reported; zero if even that is
    // unknown, which the caller treats as "ask again once a surface exists".
    if (p.displayWidthPx > 0 && p.displayHeightPx > 0) {
      width = p.displayWidthPx;
      height = p.displayHeightPx;
    }
  }
  p.primaryMonitor.mode.width = width;
  p.primaryMonitor.mode.height = height;
}

void glfwGetDesktopMode(int *width, int *height) {
  refreshDisplayMode();
  Platform &p = platform();
  if (width)
    *width = p.primaryMonitor.mode.width;
  if (height)
    *height = p.primaryMonitor.mode.height;
}

void glfwGetDesktopModeLimits(int *minWidth, int *minHeight, int *maxWidth,
                              int *maxHeight) {
  int width = 0, height = 0;
  glfwGetDesktopMode(&width, &height);
  if (minWidth)
    *minWidth = 1;
  if (minHeight)
    *minHeight = 1;
  if (maxWidth)
    *maxWidth = width;
  if (maxHeight)
    *maxHeight = height;
}

void glfwGetDesktopModeRefreshRate(int *refreshRate) {
  // Android does not report one; the compositor paces the display.
  if (refreshRate)
    *refreshRate = 60;
}

} // extern "C"

#endif // OPENCV_V4D_ANDROID